// Generated by tools/build-seed.js from decks/src/*.txt. Do not edit by hand.
window.SEED_DECKS = [
 {
  "id": "seed-pcc101-exam1",
  "version": 2,
  "name": "PCC 101 Exam 1",
  "folder": "PCC 101",
  "cards": [
   {
    "id": "seed-exam1-001",
    "term": "PCC studies the chemistry of which two things?",
    "def": "polymers and colorants"
   },
   {
    "id": "seed-exam1-002",
    "term": "Colorants include which two things?",
    "def": "dyes and pigments"
   },
   {
    "id": "seed-exam1-003",
    "term": "Main branch of chemistry PCC falls under",
    "def": "organic"
   },
   {
    "id": "seed-exam1-004",
    "term": "Branch: synthesizing an azo dye",
    "def": "organic"
   },
   {
    "id": "seed-exam1-005",
    "term": "Branch: copper ions that improve wash fastness",
    "def": "inorganic"
   },
   {
    "id": "seed-exam1-006",
    "term": "Branch: HPLC to check dye purity",
    "def": "analytical"
   },
   {
    "id": "seed-exam1-007",
    "term": "Branch: Tg and chain mobility",
    "def": "physical"
   },
   {
    "id": "seed-exam1-008",
    "term": "Branch: polymers for drug delivery",
    "def": "biochemistry"
   },
   {
    "id": "seed-exam1-009",
    "term": "Atomic number equals the number of",
    "def": "protons"
   },
   {
    "id": "seed-exam1-010",
    "term": "Neutrons =",
    "def": "mass minus protons"
   },
   {
    "id": "seed-exam1-011",
    "term": "Round the mass before subtracting?",
    "def": "yes"
   },
   {
    "id": "seed-exam1-012",
    "term": "Electrons in a neutral atom equal the number of",
    "def": "protons"
   },
   {
    "id": "seed-exam1-013",
    "term": "Element with 17 protons",
    "def": "chlorine"
   },
   {
    "id": "seed-exam1-014",
    "term": "Neutrons in chlorine (mass 35)",
    "def": "18"
   },
   {
    "id": "seed-exam1-015",
    "term": "Neutrons in aluminum (Z 13, mass 26.98)",
    "def": "14"
   },
   {
    "id": "seed-exam1-016",
    "term": "Neutrons in iron (Z 26, mass 55.85)",
    "def": "30"
   },
   {
    "id": "seed-exam1-017",
    "term": "2 or more atoms bonded together",
    "def": "molecule"
   },
   {
    "id": "seed-exam1-018",
    "term": "Atoms of 2 or more different elements bonded",
    "def": "compound"
   },
   {
    "id": "seed-exam1-019",
    "term": "NaCl: molecule, compound, or both?",
    "def": "compound"
   },
   {
    "id": "seed-exam1-020",
    "term": "O2: molecule, compound, or both?",
    "def": "molecule"
   },
   {
    "id": "seed-exam1-021",
    "term": "A dye: molecule, compound, or both?",
    "def": "both"
   },
   {
    "id": "seed-exam1-022",
    "term": "CO2: best single term",
    "def": "compound"
   },
   {
    "id": "seed-exam1-023",
    "term": "Why is NaCl not a molecule?",
    "def": "ionic lattice"
   },
   {
    "id": "seed-exam1-024",
    "term": "Shell capacities in this class",
    "def": "2, 8, 8"
   },
   {
    "id": "seed-exam1-025",
    "term": "Valence electrons for groups 13 to 18",
    "def": "group minus 10"
   },
   {
    "id": "seed-exam1-026",
    "term": "Valence electrons: carbon",
    "def": "4"
   },
   {
    "id": "seed-exam1-027",
    "term": "Valence electrons: nitrogen",
    "def": "5"
   },
   {
    "id": "seed-exam1-028",
    "term": "Valence electrons: oxygen",
    "def": "6"
   },
   {
    "id": "seed-exam1-029",
    "term": "Valence electrons: chlorine",
    "def": "7"
   },
   {
    "id": "seed-exam1-030",
    "term": "Valence electrons: hydrogen",
    "def": "1"
   },
   {
    "id": "seed-exam1-031",
    "term": "Unreactive elements with full shells",
    "def": "noble gases"
   },
   {
    "id": "seed-exam1-032",
    "term": "Most likely to bond: He, Ne, Na, or Ar",
    "def": "Na"
   },
   {
    "id": "seed-exam1-033",
    "term": "Why sodium bonds easily",
    "def": "1 valence electron"
   },
   {
    "id": "seed-exam1-034",
    "term": "Atoms bond to reach how many valence electrons?",
    "def": "8"
   },
   {
    "id": "seed-exam1-035",
    "term": "Name of the rule for 8 valence electrons",
    "def": "octet rule"
   },
   {
    "id": "seed-exam1-036",
    "term": "Strong bonds: primary or secondary?",
    "def": "primary"
   },
   {
    "id": "seed-exam1-037",
    "term": "Hydrogen bonds: primary or secondary?",
    "def": "secondary"
   },
   {
    "id": "seed-exam1-038",
    "term": "Two kinds of primary bonds",
    "def": "ionic and covalent"
   },
   {
    "id": "seed-exam1-039",
    "term": "Electrons transferred",
    "def": "ionic"
   },
   {
    "id": "seed-exam1-040",
    "term": "Electrons shared",
    "def": "covalent"
   },
   {
    "id": "seed-exam1-041",
    "term": "Ionic bonds form between a metal and a",
    "def": "nonmetal"
   },
   {
    "id": "seed-exam1-042",
    "term": "Bonds in a polymer backbone",
    "def": "covalent"
   },
   {
    "id": "seed-exam1-043",
    "term": "Acid dye bonds to nylon's amine end by what bond?",
    "def": "ionic"
   },
   {
    "id": "seed-exam1-044",
    "term": "Electronegativity increases toward which element?",
    "def": "fluorine"
   },
   {
    "id": "seed-exam1-045",
    "term": "Electronegativity direction on the table",
    "def": "up and right"
   },
   {
    "id": "seed-exam1-046",
    "term": "Highest electronegativity",
    "def": "fluorine"
   },
   {
    "id": "seed-exam1-047",
    "term": "Rank F, O, C, Na by electronegativity",
    "def": "F O C Na"
   },
   {
    "id": "seed-exam1-048",
    "term": "Bonds carbon always forms",
    "def": "4"
   },
   {
    "id": "seed-exam1-049",
    "term": "Lone pairs on carbon",
    "def": "0"
   },
   {
    "id": "seed-exam1-050",
    "term": "Lone pairs on oxygen",
    "def": "2"
   },
   {
    "id": "seed-exam1-051",
    "term": "Lone pairs on nitrogen",
    "def": "1"
   },
   {
    "id": "seed-exam1-052",
    "term": "Lone pairs on water's O",
    "def": "2"
   },
   {
    "id": "seed-exam1-053",
    "term": "Lone pairs on ammonia's N",
    "def": "1"
   },
   {
    "id": "seed-exam1-054",
    "term": "Total lone pairs in O2",
    "def": "4"
   },
   {
    "id": "seed-exam1-055",
    "term": "Bond between the two O's in O2",
    "def": "double"
   },
   {
    "id": "seed-exam1-056",
    "term": "Skeletal structure: a carbon sits at every",
    "def": "corner and end"
   },
   {
    "id": "seed-exam1-057",
    "term": "Skeletal structure: which atoms are hidden?",
    "def": "hydrogens"
   },
   {
    "id": "seed-exam1-058",
    "term": "Carbons in a zigzag of 4 lines",
    "def": "5"
   },
   {
    "id": "seed-exam1-059",
    "term": "Carbons in a zigzag of n lines",
    "def": "n + 1"
   },
   {
    "id": "seed-exam1-060",
    "term": "Hidden H on each bare benzene carbon",
    "def": "1"
   },
   {
    "id": "seed-exam1-061",
    "term": "Benzene formula",
    "def": "C6H6"
   },
   {
    "id": "seed-exam1-062",
    "term": "Phenol (benzene + OH) formula",
    "def": "C6H6O"
   },
   {
    "id": "seed-exam1-063",
    "term": "Toluene (benzene + CH3) formula",
    "def": "C7H8"
   },
   {
    "id": "seed-exam1-064",
    "term": "Pentane formula",
    "def": "C5H12"
   },
   {
    "id": "seed-exam1-065",
    "term": "Hexane formula",
    "def": "C6H14"
   },
   {
    "id": "seed-exam1-066",
    "term": "All single C-C bonds",
    "def": "alkane"
   },
   {
    "id": "seed-exam1-067",
    "term": "Has a C=C double bond",
    "def": "alkene"
   },
   {
    "id": "seed-exam1-068",
    "term": "Has a C≡C triple bond",
    "def": "alkyne"
   },
   {
    "id": "seed-exam1-069",
    "term": "Ethane: alkane, alkene, or alkyne?",
    "def": "alkane"
   },
   {
    "id": "seed-exam1-070",
    "term": "Ethylene: alkane, alkene, or alkyne?",
    "def": "alkene"
   },
   {
    "id": "seed-exam1-071",
    "term": "Acetylene: alkane, alkene, or alkyne?",
    "def": "alkyne"
   },
   {
    "id": "seed-exam1-072",
    "term": "Ethane formula",
    "def": "C2H6"
   },
   {
    "id": "seed-exam1-073",
    "term": "Ethylene formula",
    "def": "C2H4"
   },
   {
    "id": "seed-exam1-074",
    "term": "Acetylene formula",
    "def": "C2H2"
   },
   {
    "id": "seed-exam1-075",
    "term": "All single bonds: saturated or unsaturated?",
    "def": "saturated"
   },
   {
    "id": "seed-exam1-076",
    "term": "Has a double bond: saturated or unsaturated?",
    "def": "unsaturated"
   },
   {
    "id": "seed-exam1-077",
    "term": "Who proposed the Macromolecular Hypothesis?",
    "def": "Staudinger"
   },
   {
    "id": "seed-exam1-078",
    "term": "Macromolecular Hypothesis: repeat units joined by what bonds?",
    "def": "covalent"
   },
   {
    "id": "seed-exam1-079",
    "term": "Before Staudinger: polymers were clumps held by what forces?",
    "def": "weak forces"
   },
   {
    "id": "seed-exam1-080",
    "term": "Staudinger equation: memorize it?",
    "def": "no"
   },
   {
    "id": "seed-exam1-081",
    "term": "Units in a monomer",
    "def": "1"
   },
   {
    "id": "seed-exam1-082",
    "term": "Units in an oligomer",
    "def": "2 to 10"
   },
   {
    "id": "seed-exam1-083",
    "term": "Units in a polymer",
    "def": "thousands"
   },
   {
    "id": "seed-exam1-084",
    "term": "The piece in brackets that repeats n times",
    "def": "repeat unit"
   },
   {
    "id": "seed-exam1-085",
    "term": "Addition monomer template",
    "def": "H2C=CHR"
   },
   {
    "id": "seed-exam1-086",
    "term": "Monomer of polyethylene",
    "def": "ethylene"
   },
   {
    "id": "seed-exam1-087",
    "term": "Monomer of polypropylene",
    "def": "propylene"
   },
   {
    "id": "seed-exam1-088",
    "term": "Monomer of polystyrene",
    "def": "styrene"
   },
   {
    "id": "seed-exam1-089",
    "term": "Monomer of PVC",
    "def": "vinyl chloride"
   },
   {
    "id": "seed-exam1-090",
    "term": "R group of ethylene",
    "def": "H"
   },
   {
    "id": "seed-exam1-091",
    "term": "R group of propylene",
    "def": "CH3"
   },
   {
    "id": "seed-exam1-092",
    "term": "R group of styrene",
    "def": "benzene ring"
   },
   {
    "id": "seed-exam1-093",
    "term": "R group of vinyl chloride",
    "def": "Cl"
   },
   {
    "id": "seed-exam1-094",
    "term": "Polymer made from H2C=CHCl",
    "def": "PVC"
   },
   {
    "id": "seed-exam1-095",
    "term": "PE repeat unit formula",
    "def": "C2H4"
   },
   {
    "id": "seed-exam1-096",
    "term": "PP repeat unit formula",
    "def": "C3H6"
   },
   {
    "id": "seed-exam1-097",
    "term": "PS repeat unit formula",
    "def": "C8H8"
   },
   {
    "id": "seed-exam1-098",
    "term": "In addition polymerization, what opens up?",
    "def": "the double bond"
   },
   {
    "id": "seed-exam1-099",
    "term": "Addition polymerization: anything lost?",
    "def": "no"
   },
   {
    "id": "seed-exam1-100",
    "term": "Condensation polymerization loses what?",
    "def": "water"
   },
   {
    "id": "seed-exam1-101",
    "term": "Nylon-6,6: addition or condensation?",
    "def": "condensation"
   },
   {
    "id": "seed-exam1-102",
    "term": "PET: addition or condensation?",
    "def": "condensation"
   },
   {
    "id": "seed-exam1-103",
    "term": "Nylon-6,6 amine monomer",
    "def": "1,6-diaminohexane"
   },
   {
    "id": "seed-exam1-104",
    "term": "Nylon-6,6 acid monomer",
    "def": "adipic acid"
   },
   {
    "id": "seed-exam1-105",
    "term": "Carbons in each nylon-6,6 monomer",
    "def": "6"
   },
   {
    "id": "seed-exam1-106",
    "term": "Nylon-6,6 link type",
    "def": "amide"
   },
   {
    "id": "seed-exam1-107",
    "term": "Amide link atoms",
    "def": "C(=O)-NH"
   },
   {
    "id": "seed-exam1-108",
    "term": "Nylon-6,6 repeat unit formula",
    "def": "C12H22N2O2"
   },
   {
    "id": "seed-exam1-109",
    "term": "Nylon-6,6 repeat unit molar mass",
    "def": "226.32"
   },
   {
    "id": "seed-exam1-110",
    "term": "PET acid monomer",
    "def": "terephthalic acid"
   },
   {
    "id": "seed-exam1-111",
    "term": "PET alcohol monomer",
    "def": "ethylene glycol"
   },
   {
    "id": "seed-exam1-112",
    "term": "PET link type",
    "def": "ester"
   },
   {
    "id": "seed-exam1-113",
    "term": "Ester link atoms",
    "def": "C(=O)-O"
   },
   {
    "id": "seed-exam1-114",
    "term": "PET repeat unit formula",
    "def": "C10H8O4"
   },
   {
    "id": "seed-exam1-115",
    "term": "PET repeat unit molar mass",
    "def": "192.16"
   },
   {
    "id": "seed-exam1-116",
    "term": "Nylon-6,6: homopolymer or heteropolymer?",
    "def": "homopolymer"
   },
   {
    "id": "seed-exam1-117",
    "term": "Number of classification categories",
    "def": "6"
   },
   {
    "id": "seed-exam1-118",
    "term": "Classification category: natural vs synthetic",
    "def": "origin"
   },
   {
    "id": "seed-exam1-119",
    "term": "Classification category: homo vs hetero",
    "def": "monomer composition"
   },
   {
    "id": "seed-exam1-120",
    "term": "Classification category: linear vs branched",
    "def": "chain architecture"
   },
   {
    "id": "seed-exam1-121",
    "term": "Classification category: random vs block",
    "def": "monomer arrangement"
   },
   {
    "id": "seed-exam1-122",
    "term": "Classification category: thermoplastic vs thermoset",
    "def": "material behavior"
   },
   {
    "id": "seed-exam1-123",
    "term": "Classification category: crystalline vs amorphous",
    "def": "crystallinity"
   },
   {
    "id": "seed-exam1-124",
    "term": "Cellulose origin",
    "def": "natural"
   },
   {
    "id": "seed-exam1-125",
    "term": "Protein origin",
    "def": "natural"
   },
   {
    "id": "seed-exam1-126",
    "term": "Polyethylene origin",
    "def": "synthetic"
   },
   {
    "id": "seed-exam1-127",
    "term": "Nylon origin",
    "def": "synthetic"
   },
   {
    "id": "seed-exam1-128",
    "term": "Rayon origin",
    "def": "semi-synthetic"
   },
   {
    "id": "seed-exam1-129",
    "term": "Cellulose acetate origin",
    "def": "semi-synthetic"
   },
   {
    "id": "seed-exam1-130",
    "term": "Rayon is made by modifying what?",
    "def": "cellulose"
   },
   {
    "id": "seed-exam1-131",
    "term": "One type of repeat unit",
    "def": "homopolymer"
   },
   {
    "id": "seed-exam1-132",
    "term": "Two or more types of repeat unit",
    "def": "heteropolymer"
   },
   {
    "id": "seed-exam1-133",
    "term": "A protein is a heteropolymer and a",
    "def": "biopolymer"
   },
   {
    "id": "seed-exam1-134",
    "term": "Copolymer: ABABAB",
    "def": "alternating"
   },
   {
    "id": "seed-exam1-135",
    "term": "Copolymer: AAABBB",
    "def": "block"
   },
   {
    "id": "seed-exam1-136",
    "term": "Copolymer: ABBAAB",
    "def": "random"
   },
   {
    "id": "seed-exam1-137",
    "term": "Copolymer: A backbone with B side chains",
    "def": "graft"
   },
   {
    "id": "seed-exam1-138",
    "term": "Chain architecture: chains tied together",
    "def": "cross-linked"
   },
   {
    "id": "seed-exam1-139",
    "term": "Chain architecture: side branches off the main chain",
    "def": "branched"
   },
   {
    "id": "seed-exam1-140",
    "term": "Softens when heated, re-melts",
    "def": "thermoplastic"
   },
   {
    "id": "seed-exam1-141",
    "term": "Cross-linked, won't re-melt",
    "def": "thermoset"
   },
   {
    "id": "seed-exam1-142",
    "term": "Stretches and snaps back",
    "def": "elastomer"
   },
   {
    "id": "seed-exam1-143",
    "term": "Recyclable by melting: thermoplastic or thermoset?",
    "def": "thermoplastic"
   },
   {
    "id": "seed-exam1-144",
    "term": "Ordered, tightly packed chains",
    "def": "crystalline"
   },
   {
    "id": "seed-exam1-145",
    "term": "Disordered chains",
    "def": "amorphous"
   },
   {
    "id": "seed-exam1-146",
    "term": "Has both crystalline and amorphous regions",
    "def": "semi-crystalline"
   },
   {
    "id": "seed-exam1-147",
    "term": "Most polymers are",
    "def": "semi-crystalline"
   },
   {
    "id": "seed-exam1-148",
    "term": "Milk jug polyethylene",
    "def": "HDPE"
   },
   {
    "id": "seed-exam1-149",
    "term": "Plastic bag polyethylene",
    "def": "LDPE"
   },
   {
    "id": "seed-exam1-150",
    "term": "More branched: HDPE or LDPE?",
    "def": "LDPE"
   },
   {
    "id": "seed-exam1-151",
    "term": "More crystalline: HDPE or LDPE?",
    "def": "HDPE"
   },
   {
    "id": "seed-exam1-152",
    "term": "Branching makes crystallinity go",
    "def": "down"
   },
   {
    "id": "seed-exam1-153",
    "term": "Lab 1 cross-linked polymer",
    "def": "poly(acrylic acid)"
   },
   {
    "id": "seed-exam1-154",
    "term": "Cross-linked polymer in solvent or base",
    "def": "swells"
   },
   {
    "id": "seed-exam1-155",
    "term": "Repeat-unit molar mass: count atoms where?",
    "def": "inside the brackets"
   },
   {
    "id": "seed-exam1-156",
    "term": "Atomic mass of C",
    "def": "12.01"
   },
   {
    "id": "seed-exam1-157",
    "term": "Atomic mass of H",
    "def": "1.008"
   },
   {
    "id": "seed-exam1-158",
    "term": "Atomic mass of N",
    "def": "14.01"
   },
   {
    "id": "seed-exam1-159",
    "term": "Atomic mass of O",
    "def": "16.00"
   },
   {
    "id": "seed-exam1-160",
    "term": "DP stands for",
    "def": "degree of polymerization"
   },
   {
    "id": "seed-exam1-161",
    "term": "DP = polymer molar mass divided by the",
    "def": "repeat-unit molar mass"
   },
   {
    "id": "seed-exam1-162",
    "term": "Polymer molar mass = DP times the",
    "def": "repeat-unit molar mass"
   },
   {
    "id": "seed-exam1-163",
    "term": "DP is rounded to a",
    "def": "whole number"
   },
   {
    "id": "seed-exam1-164",
    "term": "DP of 50,000 g/mol polyethylene",
    "def": "1783"
   },
   {
    "id": "seed-exam1-165",
    "term": "DP of 20,000 g/mol PET",
    "def": "104"
   },
   {
    "id": "seed-exam1-166",
    "term": "Tg stands for",
    "def": "glass transition temperature"
   },
   {
    "id": "seed-exam1-167",
    "term": "Tm stands for",
    "def": "melting temperature"
   },
   {
    "id": "seed-exam1-168",
    "term": "Glassy to rubbery",
    "def": "Tg"
   },
   {
    "id": "seed-exam1-169",
    "term": "Crystalline regions melt",
    "def": "Tm"
   },
   {
    "id": "seed-exam1-170",
    "term": "Tg governs which regions?",
    "def": "amorphous"
   },
   {
    "id": "seed-exam1-171",
    "term": "Tm governs which regions?",
    "def": "crystalline"
   },
   {
    "id": "seed-exam1-172",
    "term": "Dry spaghetti: above or below Tg?",
    "def": "below"
   },
   {
    "id": "seed-exam1-173",
    "term": "Cooked spaghetti: above or below Tg?",
    "def": "above"
   },
   {
    "id": "seed-exam1-174",
    "term": "Fully amorphous polymer lacks which transition?",
    "def": "Tm"
   },
   {
    "id": "seed-exam1-175",
    "term": "Example polymer with Tg but no Tm",
    "def": "polystyrene"
   },
   {
    "id": "seed-exam1-176",
    "term": "Dye polyester above or below Tg?",
    "def": "above"
   },
   {
    "id": "seed-exam1-177",
    "term": "Free-radical mechanism on the exam?",
    "def": "no"
   }
  ]
 },
 {
  "id": "seed-pcc101-structures",
  "version": 2,
  "name": "PCC 101 Structures",
  "folder": "PCC 101",
  "cards": [
   {
    "id": "seed-struct-01",
    "term": "Structure 01: Name this molecule",
    "def": "methane",
    "termImg": "decks/pcc-structures/01.png"
   },
   {
    "id": "seed-struct-02",
    "term": "Structure 02: Name this molecule",
    "def": "water",
    "termImg": "decks/pcc-structures/02.png"
   },
   {
    "id": "seed-struct-03",
    "term": "Structure 03: Name this molecule",
    "def": "ammonia",
    "termImg": "decks/pcc-structures/03.png"
   },
   {
    "id": "seed-struct-04",
    "term": "Structure 04: Name this molecule",
    "def": "oxygen",
    "termImg": "decks/pcc-structures/04.png"
   },
   {
    "id": "seed-struct-05",
    "term": "Structure 05: Name this molecule",
    "def": "ethane",
    "termImg": "decks/pcc-structures/05.png"
   },
   {
    "id": "seed-struct-06",
    "term": "Structure 06: Name this molecule",
    "def": "ethylene",
    "termImg": "decks/pcc-structures/06.png"
   },
   {
    "id": "seed-struct-07",
    "term": "Structure 07: Name this molecule",
    "def": "acetylene",
    "termImg": "decks/pcc-structures/07.png"
   },
   {
    "id": "seed-struct-08",
    "term": "Structure 08: Skeletal. Name it",
    "def": "ethane",
    "termImg": "decks/pcc-structures/08.png"
   },
   {
    "id": "seed-struct-09",
    "term": "Structure 09: Skeletal. Name it",
    "def": "ethylene",
    "termImg": "decks/pcc-structures/09.png"
   },
   {
    "id": "seed-struct-10",
    "term": "Structure 10: Skeletal. Name it",
    "def": "acetylene",
    "termImg": "decks/pcc-structures/10.png"
   },
   {
    "id": "seed-struct-11",
    "term": "Structure 11: Skeletal. Formula?",
    "def": "C5H12",
    "termImg": "decks/pcc-structures/11.png"
   },
   {
    "id": "seed-struct-12",
    "term": "Structure 12: Skeletal. Formula?",
    "def": "C6H14",
    "termImg": "decks/pcc-structures/12.png"
   },
   {
    "id": "seed-struct-13",
    "term": "Structure 13: Name it",
    "def": "benzene",
    "termImg": "decks/pcc-structures/13.png"
   },
   {
    "id": "seed-struct-14",
    "term": "Structure 14: Name it",
    "def": "benzene",
    "termImg": "decks/pcc-structures/14.png"
   },
   {
    "id": "seed-struct-15",
    "term": "Structure 15: Formula? (count hidden H)",
    "def": "C6H6O",
    "termImg": "decks/pcc-structures/15.png"
   },
   {
    "id": "seed-struct-16",
    "term": "Structure 16: Formula? (count hidden H)",
    "def": "C7H8",
    "termImg": "decks/pcc-structures/16.png"
   },
   {
    "id": "seed-struct-17",
    "term": "Structure 17: Polymer this monomer makes",
    "def": "polyethylene",
    "termImg": "decks/pcc-structures/17.png"
   },
   {
    "id": "seed-struct-18",
    "term": "Structure 18: Polymer this monomer makes",
    "def": "polypropylene",
    "termImg": "decks/pcc-structures/18.png"
   },
   {
    "id": "seed-struct-19",
    "term": "Structure 19: Polymer this monomer makes",
    "def": "polystyrene",
    "termImg": "decks/pcc-structures/19.png"
   },
   {
    "id": "seed-struct-20",
    "term": "Structure 20: Polymer this monomer makes",
    "def": "PVC",
    "termImg": "decks/pcc-structures/20.png"
   },
   {
    "id": "seed-struct-21",
    "term": "Structure 21: Which polymer?",
    "def": "polyethylene",
    "termImg": "decks/pcc-structures/21.png"
   },
   {
    "id": "seed-struct-22",
    "term": "Structure 22: Which polymer?",
    "def": "polypropylene",
    "termImg": "decks/pcc-structures/22.png"
   },
   {
    "id": "seed-struct-23",
    "term": "Structure 23: Which polymer?",
    "def": "polystyrene",
    "termImg": "decks/pcc-structures/23.png"
   },
   {
    "id": "seed-struct-24",
    "term": "Structure 24: Which polymer?",
    "def": "PVC",
    "termImg": "decks/pcc-structures/24.png"
   },
   {
    "id": "seed-struct-25",
    "term": "Structure 25: Skeletal repeat unit. Which polymer?",
    "def": "polypropylene",
    "termImg": "decks/pcc-structures/25.png"
   },
   {
    "id": "seed-struct-26",
    "term": "Structure 26: Name this monomer",
    "def": "1,6-diaminohexane",
    "termImg": "decks/pcc-structures/26.png"
   },
   {
    "id": "seed-struct-27",
    "term": "Structure 27: Name this monomer",
    "def": "adipic acid",
    "termImg": "decks/pcc-structures/27.png"
   },
   {
    "id": "seed-struct-28",
    "term": "Structure 28: Name this monomer",
    "def": "terephthalic acid",
    "termImg": "decks/pcc-structures/28.png"
   },
   {
    "id": "seed-struct-29",
    "term": "Structure 29: Name this monomer",
    "def": "ethylene glycol",
    "termImg": "decks/pcc-structures/29.png"
   },
   {
    "id": "seed-struct-30",
    "term": "Structure 30: Name this link",
    "def": "amide",
    "termImg": "decks/pcc-structures/30.png"
   },
   {
    "id": "seed-struct-31",
    "term": "Structure 31: Name this link",
    "def": "ester",
    "termImg": "decks/pcc-structures/31.png"
   },
   {
    "id": "seed-struct-32",
    "term": "Structure 32: Which polymer?",
    "def": "nylon-6,6",
    "termImg": "decks/pcc-structures/32.png"
   },
   {
    "id": "seed-struct-33",
    "term": "Structure 33: Which polymer?",
    "def": "PET",
    "termImg": "decks/pcc-structures/33.png"
   }
  ]
 }
];
