// Generated by tools/build-seed.js from decks/src/*.txt. Do not edit by hand.
window.SEED_DECKS = [
 {
  "id": "seed-pcc101-exam1",
  "version": 4,
  "name": "PCC 101 Exam 1",
  "folder": "PCC 101",
  "cards": [
   {
    "id": "seed-core-001",
    "term": "PCC studies the chemistry of which two things?",
    "def": "polymers and colorants",
    "fakes": [
     "monomers and pigments",
     "resins and dyes",
     "plastics and paints",
     "fibers and colorants",
     "polymers and metals",
     "colorants and adhesives",
     "polymers and coatings",
     "dyes and solvents"
    ]
   },
   {
    "id": "seed-core-002",
    "term": "Electronegativity increases toward which element?",
    "def": "fluorine",
    "fakes": [
     "chlorine",
     "nitrogen",
     "carbon",
     "francium",
     "hydrogen",
     "sodium",
     "neon",
     "argon"
    ]
   },
   {
    "id": "seed-core-003",
    "term": "Rank F, O, C, Na by electronegativity",
    "def": "F O C Na",
    "fakes": [
     "Na O C F",
     "F O Na C",
     "Na C O F",
     "O C F Na",
     "Na F O C"
    ]
   },
   {
    "id": "seed-core-004",
    "term": "Hydrogen bonds: primary or secondary?",
    "def": "secondary",
    "fakes": [
     "primary",
     "both equally",
     "neither",
     "tertiary",
     "ionic",
     "covalent",
     "metallic",
     "van der Waals only"
    ]
   },
   {
    "id": "seed-core-005",
    "term": "Acid dye bonds to nylon's amine end by what bond?",
    "def": "ionic",
    "fakes": [
     "covalent",
     "hydrogen",
     "van der Waals",
     "metallic",
     "dipole",
     "coordinate covalent",
     "amide",
     "ester"
    ]
   },
   {
    "id": "seed-core-006",
    "term": "Carbons in a zigzag of 4 lines",
    "def": "5",
    "fakes": [
     "4",
     "3",
     "6",
     "7",
     "8",
     "2",
     "9",
     "10"
    ]
   },
   {
    "id": "seed-core-007",
    "term": "Hidden H on each bare benzene carbon",
    "def": "1",
    "fakes": [
     "2",
     "3",
     "4",
     "0",
     "6",
     "5",
     "8",
     "7"
    ]
   },
   {
    "id": "seed-core-008",
    "term": "Phenol (benzene + OH) formula",
    "def": "C6H6O",
    "fakes": [
     "C6H4O2",
     "C6H7O",
     "C7H6O",
     "C6H6O2",
     "C5H4O",
     "C6H8O2",
     "C6H5O",
     "C7H8O"
    ]
   },
   {
    "id": "seed-core-009",
    "term": "Toluene (benzene + CH3) formula",
    "def": "C7H8",
    "fakes": [
     "C6H8",
     "C7H6",
     "C8H10",
     "C7H10",
     "C6H6",
     "C8H8",
     "C7H14",
     "C6H10"
    ]
   },
   {
    "id": "seed-core-010",
    "term": "All single C-C bonds",
    "def": "alkane",
    "fakes": [
     "aromatic",
     "polymer",
     "monomer",
     "diene",
     "unsaturated hydrocarbon",
     "aromatic ring"
    ]
   },
   {
    "id": "seed-core-011",
    "term": "Has a C=C double bond",
    "def": "alkene",
    "fakes": [
     "aromatic",
     "polymer",
     "monomer",
     "diene only",
     "saturated hydrocarbon",
     "cycloalkane"
    ]
   },
   {
    "id": "seed-core-012",
    "term": "Has a C≡C triple bond",
    "def": "alkyne",
    "fakes": [
     "aromatic",
     "polymer",
     "monomer",
     "diene",
     "saturated hydrocarbon",
     "cycloalkane"
    ]
   },
   {
    "id": "seed-core-013",
    "term": "Has a double bond: saturated or unsaturated?",
    "def": "unsaturated",
    "fakes": [
     "aromatic",
     "partially saturated",
     "crystalline",
     "amorphous",
     "conjugated",
     "cross-linked",
     "branched"
    ]
   },
   {
    "id": "seed-core-014",
    "term": "Who proposed the Macromolecular Hypothesis?",
    "def": "Staudinger",
    "fakes": [
     "Carothers",
     "Ziegler",
     "Natta",
     "Flory",
     "Avogadro",
     "Dalton",
     "Mendeleev",
     "Pauling"
    ]
   },
   {
    "id": "seed-core-015",
    "term": "Macromolecular Hypothesis: repeat units joined by what bonds?",
    "def": "covalent",
    "fakes": [
     "ionic",
     "hydrogen",
     "metallic",
     "van der Waals",
     "dipole-dipole",
     "weak forces",
     "coordinate",
     "London dispersion"
    ]
   },
   {
    "id": "seed-core-016",
    "term": "Before Staudinger: polymers were clumps held by what forces?",
    "def": "weak forces",
    "fakes": [
     "covalent bonds",
     "ionic bonds",
     "strong forces",
     "metallic bonds",
     "coordinate bonds",
     "amide bonds",
     "ester bonds",
     "peptide bonds"
    ]
   },
   {
    "id": "seed-core-017",
    "term": "Units in an oligomer",
    "def": "2 to 10",
    "fakes": [
     "1",
     "10 to 100",
     "thousands",
     "100 to 1000",
     "1 to 2",
     "20 to 50",
     "50 to 100",
     "12 to 20"
    ]
   },
   {
    "id": "seed-core-018",
    "term": "Units in a polymer",
    "def": "thousands",
    "fakes": [
     "hundreds",
     "2 to 10",
     "1",
     "tens",
     "millions",
     "10 to 100",
     "dozens",
     "100"
    ]
   },
   {
    "id": "seed-core-019",
    "term": "Addition monomer template",
    "def": "H2C=CHR",
    "fakes": [
     "HC≡CR",
     "H2C-CH2R",
     "RHC=CHR",
     "H2N-R-COOH",
     "HOOC-R-COOH",
     "H2C=CR2",
     "RCH2-CH2R",
     "HO-R-OH"
    ]
   },
   {
    "id": "seed-core-020",
    "term": "R group of propylene",
    "def": "CH3",
    "fakes": [
     "H",
     "Cl",
     "benzene ring",
     "C2H5",
     "OH",
     "CH2",
     "C3H7",
     "F"
    ]
   },
   {
    "id": "seed-core-021",
    "term": "R group of styrene",
    "def": "benzene ring",
    "fakes": [
     "CH3",
     "Cl",
     "H",
     "phenol group",
     "naphthalene ring",
     "OH",
     "C2H5",
     "cyclohexane ring"
    ]
   },
   {
    "id": "seed-core-022",
    "term": "Polymer made from H2C=CHCl",
    "def": "PVC",
    "fakes": [
     "PE",
     "PP",
     "PS",
     "PET",
     "nylon-6,6",
     "PVA",
     "PTFE",
     "PVDC"
    ]
   },
   {
    "id": "seed-core-023",
    "term": "In addition polymerization, what opens up?",
    "def": "the double bond",
    "fakes": [
     "the triple bond",
     "the ring",
     "the ester bond",
     "the amide bond",
     "a single bond",
     "the benzene ring",
     "the hydroxyl group",
     "the carbonyl group"
    ]
   },
   {
    "id": "seed-core-024",
    "term": "Condensation polymerization loses what?",
    "def": "water",
    "fakes": [
     "HCl",
     "ammonia",
     "nothing",
     "oxygen",
     "ethylene glycol",
     "methanol",
     "carbon dioxide",
     "hydrogen"
    ]
   },
   {
    "id": "seed-core-025",
    "term": "Nylon-6,6 amine monomer",
    "def": "1,6-diaminohexane",
    "fakes": [
     "1,4-diaminobutane",
     "1,8-diaminooctane",
     "ethylenediamine",
     "adipic acid",
     "terephthalic acid",
     "1,6-hexanediol",
     "1,5-diaminopentane",
     "ethylene glycol"
    ]
   },
   {
    "id": "seed-core-026",
    "term": "Nylon-6,6 acid monomer",
    "def": "adipic acid",
    "fakes": [
     "terephthalic acid",
     "sebacic acid",
     "succinic acid",
     "1,6-diaminohexane",
     "ethylene glycol",
     "oxalic acid",
     "glutaric acid",
     "phthalic acid"
    ]
   },
   {
    "id": "seed-core-027",
    "term": "Nylon-6,6 link type",
    "def": "amide",
    "fakes": [
     "ester",
     "ether",
     "urethane",
     "carbonate",
     "anhydride",
     "hydrogen bond"
    ]
   },
   {
    "id": "seed-core-028",
    "term": "PET acid monomer",
    "def": "terephthalic acid",
    "fakes": [
     "adipic acid",
     "phthalic acid",
     "isophthalic acid",
     "benzoic acid",
     "oxalic acid",
     "succinic acid",
     "sebacic acid",
     "ethylene glycol"
    ]
   },
   {
    "id": "seed-core-029",
    "term": "PET alcohol monomer",
    "def": "ethylene glycol",
    "fakes": [
     "propylene glycol",
     "methanol",
     "ethanol",
     "1,6-hexanediol",
     "glycerol",
     "ethylene oxide",
     "terephthalic acid"
    ]
   },
   {
    "id": "seed-core-030",
    "term": "PET link type",
    "def": "ester",
    "fakes": [
     "amide",
     "ether",
     "urethane",
     "imide",
     "carbonate",
     "anhydride",
     "hydrogen bond",
     "amine"
    ]
   },
   {
    "id": "seed-core-031",
    "term": "Nylon-6,6: homopolymer or heteropolymer?",
    "def": "homopolymer",
    "fakes": [
     "heteropolymer",
     "copolymer",
     "block copolymer",
     "random copolymer",
     "alternating copolymer",
     "biopolymer",
     "graft copolymer",
     "cross-linked polymer"
    ]
   },
   {
    "id": "seed-core-032",
    "term": "Classification category: natural vs synthetic",
    "def": "origin",
    "fakes": [
     "chain architecture",
     "monomer composition",
     "monomer arrangement",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-core-033",
    "term": "Classification category: homo vs hetero",
    "def": "monomer composition",
    "fakes": [
     "origin",
     "chain architecture",
     "monomer arrangement",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-core-034",
    "term": "Classification category: linear vs branched",
    "def": "chain architecture",
    "fakes": [
     "origin",
     "monomer composition",
     "monomer arrangement",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-core-035",
    "term": "Classification category: random vs block",
    "def": "monomer arrangement",
    "fakes": [
     "origin",
     "monomer composition",
     "chain architecture",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-core-036",
    "term": "Classification category: thermoplastic vs thermoset",
    "def": "material behavior",
    "fakes": [
     "origin",
     "monomer composition",
     "chain architecture",
     "monomer arrangement",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-core-037",
    "term": "Classification category: crystalline vs amorphous",
    "def": "crystallinity",
    "fakes": [
     "origin",
     "monomer composition",
     "chain architecture",
     "monomer arrangement",
     "material behavior",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-core-038",
    "term": "Rayon origin",
    "def": "semi-synthetic",
    "fakes": [
     "natural",
     "synthetic",
     "biopolymer",
     "fully synthetic",
     "man-made",
     "petroleum-based",
     "naturally occurring",
     "animal-derived"
    ]
   },
   {
    "id": "seed-core-039",
    "term": "Rayon is made by modifying what?",
    "def": "cellulose",
    "fakes": [
     "starch",
     "protein",
     "petroleum",
     "ethylene",
     "collagen",
     "chitin",
     "lignin",
     "keratin"
    ]
   },
   {
    "id": "seed-core-040",
    "term": "One type of repeat unit",
    "def": "homopolymer",
    "fakes": [
     "heteropolymer",
     "copolymer",
     "block copolymer",
     "random copolymer",
     "alternating copolymer",
     "graft copolymer",
     "biopolymer",
     "oligomer"
    ]
   },
   {
    "id": "seed-core-041",
    "term": "Two or more types of repeat unit",
    "def": "heteropolymer",
    "fakes": [
     "homopolymer",
     "monomer",
     "oligomer",
     "biopolymer",
     "cross-linked polymer",
     "thermoplastic",
     "thermoset",
     "branched polymer"
    ]
   },
   {
    "id": "seed-core-042",
    "term": "A protein is a heteropolymer and a",
    "def": "biopolymer",
    "fakes": [
     "homopolymer",
     "thermoplastic",
     "thermoset",
     "monomer",
     "oligomer",
     "synthetic polymer",
     "cross-linked polymer",
     "elastomer"
    ]
   },
   {
    "id": "seed-core-043",
    "term": "Copolymer: ABABAB",
    "def": "alternating",
    "fakes": [
     "block",
     "random",
     "graft",
     "homopolymer",
     "branched",
     "cross-linked",
     "star",
     "comb"
    ]
   },
   {
    "id": "seed-core-044",
    "term": "Copolymer: AAABBB",
    "def": "block",
    "fakes": [
     "alternating",
     "random",
     "graft",
     "homopolymer",
     "branched",
     "cross-linked",
     "star",
     "linear"
    ]
   },
   {
    "id": "seed-core-045",
    "term": "Copolymer: ABBAAB",
    "def": "random",
    "fakes": [
     "alternating",
     "block",
     "graft",
     "homopolymer",
     "branched",
     "cross-linked",
     "star",
     "linear"
    ]
   },
   {
    "id": "seed-core-046",
    "term": "Copolymer: A backbone with B side chains",
    "def": "graft",
    "fakes": [
     "alternating",
     "block",
     "random",
     "cross-linked",
     "star",
     "linear",
     "homopolymer",
     "thermoset"
    ]
   },
   {
    "id": "seed-core-047",
    "term": "Chain architecture: chains tied together",
    "def": "cross-linked",
    "fakes": [
     "branched",
     "linear",
     "graft",
     "star",
     "random",
     "alternating",
     "block",
     "ladder"
    ]
   },
   {
    "id": "seed-core-048",
    "term": "Chain architecture: side branches off the main chain",
    "def": "branched",
    "fakes": [
     "linear",
     "cross-linked",
     "star",
     "random",
     "alternating",
     "block",
     "ladder",
     "network"
    ]
   },
   {
    "id": "seed-core-049",
    "term": "Softens when heated, re-melts",
    "def": "thermoplastic",
    "fakes": [
     "thermoset",
     "crystalline",
     "amorphous",
     "elastomer",
     "cross-linked",
     "biopolymer",
     "copolymer",
     "homopolymer"
    ]
   },
   {
    "id": "seed-core-050",
    "term": "Cross-linked, won't re-melt",
    "def": "thermoset",
    "fakes": [
     "thermoplastic",
     "elastomer",
     "semi-crystalline",
     "amorphous",
     "crystalline",
     "copolymer",
     "homopolymer",
     "monomer"
    ]
   },
   {
    "id": "seed-core-051",
    "term": "Stretches and snaps back",
    "def": "elastomer",
    "fakes": [
     "thermoset",
     "thermoplastic",
     "crystalline",
     "amorphous",
     "semi-crystalline",
     "copolymer",
     "homopolymer",
     "plasticizer"
    ]
   },
   {
    "id": "seed-core-052",
    "term": "Ordered, tightly packed chains",
    "def": "crystalline",
    "fakes": [
     "amorphous",
     "semi-crystalline",
     "thermoset",
     "elastomer",
     "branched",
     "cross-linked",
     "thermoplastic",
     "glassy"
    ]
   },
   {
    "id": "seed-core-053",
    "term": "Disordered chains",
    "def": "amorphous",
    "fakes": [
     "crystalline",
     "semi-crystalline",
     "cross-linked",
     "thermoset",
     "helical",
     "linear",
     "thermoplastic",
     "elastomeric"
    ]
   },
   {
    "id": "seed-core-054",
    "term": "Has both crystalline and amorphous regions",
    "def": "semi-crystalline",
    "fakes": [
     "crystalline",
     "amorphous",
     "thermoset",
     "elastomer",
     "copolymer",
     "homopolymer",
     "cross-linked",
     "glassy"
    ]
   },
   {
    "id": "seed-core-055",
    "term": "More branched: HDPE or LDPE?",
    "def": "LDPE",
    "fakes": [
     "both equally",
     "neither",
     "PP",
     "PET",
     "PVC",
     "PS"
    ]
   },
   {
    "id": "seed-core-056",
    "term": "More crystalline: HDPE or LDPE?",
    "def": "HDPE",
    "fakes": [
     "both equally",
     "neither",
     "PP",
     "PET",
     "PVC",
     "PS",
     "LLDPE"
    ]
   },
   {
    "id": "seed-core-057",
    "term": "Cross-linked polymer in solvent or base",
    "def": "swells",
    "fakes": [
     "dissolves",
     "melts",
     "shrinks",
     "crystallizes",
     "evaporates",
     "decomposes",
     "hardens",
     "liquefies"
    ]
   },
   {
    "id": "seed-core-058",
    "term": "Repeat-unit molar mass: count atoms where?",
    "def": "inside the brackets",
    "fakes": [
     "across the whole chain",
     "at the chain ends",
     "in the side groups only",
     "in the backbone only",
     "per monomer pair",
     "outside the parentheses",
     "at the crosslink points"
    ]
   },
   {
    "id": "seed-core-059",
    "term": "DP = polymer molar mass divided by the",
    "def": "repeat-unit molar mass",
    "fakes": [
     "monomer count",
     "number of chains",
     "total molar mass",
     "molecular weight of solvent",
     "DP squared",
     "number of repeat units",
     "Avogadro's number",
     "chain length"
    ]
   },
   {
    "id": "seed-core-060",
    "term": "DP is rounded to a",
    "def": "whole number",
    "fakes": [
     "decimal",
     "percentage",
     "fraction",
     "power of ten",
     "nearest hundred",
     "nearest thousand",
     "negative number",
     "ratio"
    ]
   },
   {
    "id": "seed-core-061",
    "term": "DP of 50,000 g/mol polyethylene",
    "def": "1783",
    "fakes": [
     "1428",
     "1250",
     "892",
     "3571",
     "2000",
     "1000",
     "500",
     "3566"
    ]
   },
   {
    "id": "seed-core-062",
    "term": "Tg stands for",
    "def": "glass transition temperature",
    "fakes": [
     "melting temperature",
     "gelation temperature",
     "glass transformation time",
     "growth temperature",
     "gel point temperature",
     "glassy tensile strength",
     "global temperature"
    ]
   },
   {
    "id": "seed-core-063",
    "term": "Glassy to rubbery",
    "def": "Tg",
    "fakes": [
     "Tm",
     "Td",
     "Tc",
     "Tb",
     "Tx",
     "boiling point",
     "melting point",
     "flash point"
    ]
   },
   {
    "id": "seed-core-064",
    "term": "Crystalline regions melt",
    "def": "Tm",
    "fakes": [
     "Tg",
     "Td",
     "Tc",
     "Tb",
     "Tx",
     "boiling point",
     "glass transition",
     "decomposition point"
    ]
   },
   {
    "id": "seed-core-065",
    "term": "Tg governs which regions?",
    "def": "amorphous",
    "fakes": [
     "crystalline",
     "semi-crystalline",
     "cross-linked",
     "both regions",
     "neither region",
     "linear regions",
     "branched regions",
     "elastomeric regions"
    ]
   },
   {
    "id": "seed-core-066",
    "term": "Tm governs which regions?",
    "def": "crystalline",
    "fakes": [
     "amorphous",
     "semi-crystalline",
     "cross-linked",
     "both regions",
     "neither region",
     "glassy regions only",
     "branched regions",
     "elastomeric regions"
    ]
   },
   {
    "id": "seed-core-067",
    "term": "Fully amorphous polymer lacks which transition?",
    "def": "Tm",
    "fakes": [
     "Tg",
     "Td",
     "Tc",
     "Tb",
     "Tx",
     "boiling point",
     "decomposition point",
     "flash point"
    ]
   },
   {
    "id": "seed-core-068",
    "term": "Example polymer with Tg but no Tm",
    "def": "polystyrene",
    "fakes": [
     "polyethylene",
     "polypropylene",
     "PET",
     "nylon-6,6",
     "HDPE",
     "LDPE",
     "UHMWPE",
     "PP"
    ]
   },
   {
    "id": "seed-core-069",
    "term": "Dye polyester above or below Tg?",
    "def": "above",
    "fakes": [
     "below",
     "at",
     "near",
     "well below",
     "equal to",
     "unrelated to",
     "below Tm",
     "at Tm"
    ]
   },
   {
    "id": "seed-struct-01",
    "term": "Structure 01: Name this molecule",
    "def": "methane",
    "termImg": "decks/pcc-structures/01.png",
    "fakes": [
     "methanol",
     "ammonia",
     "water",
     "propane",
     "methylene",
     "formaldehyde",
     "ethylene"
    ]
   },
   {
    "id": "seed-struct-02",
    "term": "Structure 02: Name this molecule",
    "def": "water",
    "termImg": "decks/pcc-structures/02.png",
    "fakes": [
     "methane",
     "ammonia",
     "hydrogen peroxide",
     "methanol",
     "oxygen",
     "ethanol",
     "carbon dioxide",
     "hydronium"
    ]
   },
   {
    "id": "seed-struct-03",
    "term": "Structure 03: Name this molecule",
    "def": "ammonia",
    "termImg": "decks/pcc-structures/03.png",
    "fakes": [
     "methane",
     "water",
     "methylamine",
     "hydrazine",
     "nitrogen",
     "amine",
     "urea",
     "hydroxylamine"
    ]
   },
   {
    "id": "seed-struct-04",
    "term": "Structure 04: Name this molecule",
    "def": "oxygen",
    "termImg": "decks/pcc-structures/04.png",
    "fakes": [
     "nitrogen",
     "ozone",
     "water",
     "hydrogen",
     "carbon dioxide",
     "methane",
     "hydrogen peroxide",
     "sulfur dioxide"
    ]
   },
   {
    "id": "seed-struct-05",
    "term": "Structure 05: Name this molecule",
    "def": "ethane",
    "termImg": "decks/pcc-structures/05.png",
    "fakes": [
     "ethylene",
     "propane",
     "acetylene",
     "methanol",
     "ethanol",
     "butane"
    ]
   },
   {
    "id": "seed-struct-06",
    "term": "Structure 06: Name this molecule",
    "def": "ethylene",
    "termImg": "decks/pcc-structures/06.png",
    "fakes": [
     "ethane",
     "acetylene",
     "propylene",
     "methane",
     "ethanol",
     "butylene",
     "propane",
     "vinyl chloride"
    ]
   },
   {
    "id": "seed-struct-07",
    "term": "Structure 07: Name this molecule",
    "def": "acetylene",
    "termImg": "decks/pcc-structures/07.png",
    "fakes": [
     "ethylene",
     "ethane",
     "propyne",
     "methane",
     "butyne",
     "propylene",
     "benzene",
     "ethanol"
    ]
   },
   {
    "id": "seed-struct-08",
    "term": "Structure 08: Skeletal. Name it",
    "def": "ethane",
    "termImg": "decks/pcc-structures/08.png",
    "fakes": [
     "ethylene",
     "propane",
     "acetylene",
     "methanol",
     "butane",
     "ethanol",
     "propylene"
    ]
   },
   {
    "id": "seed-struct-09",
    "term": "Structure 09: Skeletal. Name it",
    "def": "ethylene",
    "termImg": "decks/pcc-structures/09.png",
    "fakes": [
     "ethane",
     "acetylene",
     "propylene",
     "methane",
     "butylene",
     "propane",
     "vinyl chloride",
     "ethanol"
    ]
   },
   {
    "id": "seed-struct-10",
    "term": "Structure 10: Skeletal. Name it",
    "def": "acetylene",
    "termImg": "decks/pcc-structures/10.png",
    "fakes": [
     "ethylene",
     "ethane",
     "propyne",
     "methane",
     "butyne",
     "propylene",
     "benzene",
     "ethanol"
    ]
   },
   {
    "id": "seed-struct-11",
    "term": "Structure 11: Skeletal. Formula?",
    "def": "C5H12",
    "termImg": "decks/pcc-structures/11.png",
    "fakes": [
     "C5H10",
     "C5H14",
     "C4H10",
     "C6H14",
     "C5H11",
     "C6H12",
     "C4H8",
     "C5H13"
    ]
   },
   {
    "id": "seed-struct-12",
    "term": "Structure 12: Skeletal. Formula?",
    "def": "C6H14",
    "termImg": "decks/pcc-structures/12.png",
    "fakes": [
     "C6H12",
     "C6H16",
     "C5H12",
     "C7H16",
     "C6H13",
     "C7H14",
     "C5H10",
     "C6H15"
    ]
   },
   {
    "id": "seed-struct-13",
    "term": "Structure 13: Name it",
    "def": "benzene",
    "termImg": "decks/pcc-structures/13.png",
    "fakes": [
     "cyclohexane",
     "toluene",
     "naphthalene",
     "phenol",
     "cyclohexene",
     "styrene",
     "xylene",
     "pyridine"
    ]
   },
   {
    "id": "seed-struct-14",
    "term": "Structure 14: Name it",
    "def": "benzene",
    "termImg": "decks/pcc-structures/14.png",
    "fakes": [
     "cyclohexane",
     "toluene",
     "naphthalene",
     "phenol",
     "cyclohexene",
     "styrene",
     "xylene",
     "pyridine"
    ]
   },
   {
    "id": "seed-struct-15",
    "term": "Structure 15: Formula? (count hidden H)",
    "def": "C6H6O",
    "termImg": "decks/pcc-structures/15.png",
    "fakes": [
     "C6H8O",
     "C7H8O",
     "C6H6O2",
     "C5H6O",
     "C6H4O",
     "C7H6O",
     "C6H10O"
    ]
   },
   {
    "id": "seed-struct-16",
    "term": "Structure 16: Formula? (count hidden H)",
    "def": "C7H8",
    "termImg": "decks/pcc-structures/16.png",
    "fakes": [
     "C7H6",
     "C7H10",
     "C6H6",
     "C8H10",
     "C6H8",
     "C8H8",
     "C7H9"
    ]
   },
   {
    "id": "seed-struct-17",
    "term": "Structure 17: Polymer this monomer makes",
    "def": "polyethylene",
    "termImg": "decks/pcc-structures/17.png",
    "fakes": [
     "polypropylene",
     "polystyrene",
     "PVC",
     "PET",
     "nylon-6,6",
     "polybutylene",
     "polyisobutylene",
     "poly(vinyl acetate)"
    ]
   },
   {
    "id": "seed-struct-18",
    "term": "Structure 18: Polymer this monomer makes",
    "def": "polypropylene",
    "termImg": "decks/pcc-structures/18.png",
    "fakes": [
     "polyethylene",
     "polystyrene",
     "PVC",
     "PET",
     "nylon-6,6",
     "polybutylene",
     "poly(vinyl acetate)",
     "polyisoprene"
    ]
   },
   {
    "id": "seed-struct-19",
    "term": "Structure 19: Polymer this monomer makes",
    "def": "polystyrene",
    "termImg": "decks/pcc-structures/19.png",
    "fakes": [
     "polyethylene",
     "polypropylene",
     "PVC",
     "PET",
     "nylon-6,6",
     "poly(vinyl acetate)",
     "polybutadiene",
     "polyisoprene"
    ]
   },
   {
    "id": "seed-struct-20",
    "term": "Structure 20: Polymer this monomer makes",
    "def": "PVC",
    "termImg": "decks/pcc-structures/20.png",
    "fakes": [
     "polyethylene",
     "polypropylene",
     "polystyrene",
     "PET",
     "nylon-6,6",
     "poly(vinylidene chloride)",
     "poly(vinyl acetate)",
     "PTFE"
    ]
   },
   {
    "id": "seed-struct-21",
    "term": "Structure 21: Which polymer?",
    "def": "polyethylene",
    "termImg": "decks/pcc-structures/21.png",
    "fakes": [
     "polypropylene",
     "polystyrene",
     "PVC",
     "PET",
     "nylon-6,6",
     "polybutylene",
     "poly(vinyl acetate)",
     "PTFE"
    ]
   },
   {
    "id": "seed-struct-22",
    "term": "Structure 22: Which polymer?",
    "def": "polypropylene",
    "termImg": "decks/pcc-structures/22.png",
    "fakes": [
     "polyethylene",
     "polystyrene",
     "PVC",
     "PET",
     "nylon-6,6",
     "polybutylene",
     "poly(vinyl acetate)",
     "polyisobutylene"
    ]
   },
   {
    "id": "seed-struct-23",
    "term": "Structure 23: Which polymer?",
    "def": "polystyrene",
    "termImg": "decks/pcc-structures/23.png",
    "fakes": [
     "polyethylene",
     "polypropylene",
     "PVC",
     "PET",
     "nylon-6,6",
     "poly(vinyl acetate)",
     "polybutadiene",
     "polyisoprene"
    ]
   },
   {
    "id": "seed-struct-24",
    "term": "Structure 24: Which polymer?",
    "def": "PVC",
    "termImg": "decks/pcc-structures/24.png",
    "fakes": [
     "polyethylene",
     "polypropylene",
     "polystyrene",
     "PET",
     "nylon-6,6",
     "poly(vinylidene chloride)",
     "poly(vinyl acetate)",
     "PTFE"
    ]
   },
   {
    "id": "seed-struct-25",
    "term": "Structure 25: Skeletal repeat unit. Which polymer?",
    "def": "polypropylene",
    "termImg": "decks/pcc-structures/25.png",
    "fakes": [
     "polyethylene",
     "polystyrene",
     "PVC",
     "PET",
     "nylon-6,6",
     "polybutylene",
     "poly(vinyl acetate)",
     "polyisobutylene"
    ]
   },
   {
    "id": "seed-struct-26",
    "term": "Structure 26: Name this monomer",
    "def": "1,6-diaminohexane",
    "termImg": "decks/pcc-structures/26.png",
    "fakes": [
     "1,4-diaminobutane",
     "1,2-diaminoethane",
     "1,8-diaminooctane",
     "caprolactam",
     "adipic acid",
     "terephthalic acid",
     "ethylene glycol",
     "sebacic acid"
    ]
   },
   {
    "id": "seed-struct-27",
    "term": "Structure 27: Name this monomer",
    "def": "adipic acid",
    "termImg": "decks/pcc-structures/27.png",
    "fakes": [
     "terephthalic acid",
     "sebacic acid",
     "1,6-diaminohexane",
     "ethylene glycol",
     "succinic acid",
     "oxalic acid",
     "caprolactam",
     "malonic acid"
    ]
   },
   {
    "id": "seed-struct-28",
    "term": "Structure 28: Name this monomer",
    "def": "terephthalic acid",
    "termImg": "decks/pcc-structures/28.png",
    "fakes": [
     "adipic acid",
     "isophthalic acid",
     "ethylene glycol",
     "1,6-diaminohexane",
     "benzoic acid",
     "phthalic acid",
     "sebacic acid",
     "caprolactam"
    ]
   },
   {
    "id": "seed-struct-29",
    "term": "Structure 29: Name this monomer",
    "def": "ethylene glycol",
    "termImg": "decks/pcc-structures/29.png",
    "fakes": [
     "propylene glycol",
     "adipic acid",
     "terephthalic acid",
     "1,6-diaminohexane",
     "methanol",
     "glycerol",
     "ethanol"
    ]
   },
   {
    "id": "seed-struct-30",
    "term": "Structure 30: Name this link",
    "def": "amide",
    "termImg": "decks/pcc-structures/30.png",
    "fakes": [
     "ester",
     "ether",
     "urethane",
     "anhydride",
     "carbonate",
     "carboxylic acid"
    ]
   },
   {
    "id": "seed-struct-31",
    "term": "Structure 31: Name this link",
    "def": "ester",
    "termImg": "decks/pcc-structures/31.png",
    "fakes": [
     "amide",
     "ether",
     "urethane",
     "imide",
     "anhydride",
     "carbonate",
     "carboxylic acid",
     "amine"
    ]
   },
   {
    "id": "seed-struct-32",
    "term": "Structure 32: Which polymer?",
    "def": "nylon-6,6",
    "termImg": "decks/pcc-structures/32.png",
    "fakes": [
     "nylon-6",
     "PET",
     "polystyrene",
     "polyethylene",
     "Kevlar",
     "polypropylene",
     "PVC",
     "polyurethane"
    ]
   },
   {
    "id": "seed-struct-33",
    "term": "Structure 33: Which polymer?",
    "def": "PET",
    "termImg": "decks/pcc-structures/33.png",
    "fakes": [
     "nylon-6,6",
     "polystyrene",
     "polyethylene",
     "PVC",
     "polypropylene",
     "PBT",
     "polycarbonate",
     "poly(vinyl acetate)"
    ]
   }
  ]
 },
 {
  "id": "seed-pcc101-exam1-full",
  "version": 2,
  "name": "PCC 101 Exam 1 (all 177 text cards)",
  "folder": "PCC 101",
  "cards": [
   {
    "id": "seed-full-001",
    "term": "PCC studies the chemistry of which two things?",
    "def": "polymers and colorants",
    "fakes": [
     "monomers and pigments",
     "resins and dyes",
     "plastics and paints",
     "fibers and colorants",
     "polymers and metals",
     "colorants and adhesives",
     "polymers and coatings",
     "dyes and solvents"
    ]
   },
   {
    "id": "seed-full-002",
    "term": "Colorants include which two things?",
    "def": "dyes and pigments",
    "fakes": [
     "dyes and polymers",
     "pigments and monomers",
     "dyes and solvents",
     "pigments and resins",
     "inks and dyes",
     "pigments and catalysts",
     "dyes and additives",
     "pigments and plasticizers"
    ]
   },
   {
    "id": "seed-full-003",
    "term": "Main branch of chemistry PCC falls under",
    "def": "organic",
    "fakes": [
     "inorganic",
     "physical",
     "analytical",
     "biochemistry",
     "polymer",
     "environmental",
     "nuclear",
     "quantum"
    ]
   },
   {
    "id": "seed-full-004",
    "term": "Branch: synthesizing an azo dye",
    "def": "organic",
    "fakes": [
     "inorganic",
     "physical",
     "analytical",
     "biochemistry",
     "nuclear",
     "environmental",
     "quantum",
     "polymer"
    ]
   },
   {
    "id": "seed-full-005",
    "term": "Branch: copper ions that improve wash fastness",
    "def": "inorganic",
    "fakes": [
     "physical",
     "analytical",
     "biochemistry",
     "nuclear",
     "environmental",
     "quantum",
     "polymer"
    ]
   },
   {
    "id": "seed-full-006",
    "term": "Branch: HPLC to check dye purity",
    "def": "analytical",
    "fakes": [
     "organic",
     "inorganic",
     "physical",
     "biochemistry",
     "nuclear",
     "environmental",
     "quantum",
     "polymer"
    ]
   },
   {
    "id": "seed-full-007",
    "term": "Branch: Tg and chain mobility",
    "def": "physical",
    "fakes": [
     "organic",
     "inorganic",
     "analytical",
     "biochemistry",
     "nuclear",
     "environmental",
     "quantum",
     "polymer"
    ]
   },
   {
    "id": "seed-full-008",
    "term": "Branch: polymers for drug delivery",
    "def": "biochemistry",
    "fakes": [
     "organic",
     "inorganic",
     "physical",
     "analytical",
     "nuclear",
     "environmental",
     "quantum",
     "polymer"
    ]
   },
   {
    "id": "seed-full-009",
    "term": "Atomic number equals the number of",
    "def": "protons",
    "fakes": [
     "neutrons",
     "protons plus neutrons",
     "protons plus electrons",
     "nucleons",
     "valence electrons",
     "isotopes",
     "mass units",
     "the group number"
    ]
   },
   {
    "id": "seed-full-010",
    "term": "Neutrons =",
    "def": "mass minus protons",
    "fakes": [
     "protons minus mass",
     "atomic number minus mass",
     "mass divided by protons",
     "protons plus mass",
     "electrons minus protons",
     "electrons times mass"
    ]
   },
   {
    "id": "seed-full-011",
    "term": "Round the mass before subtracting?",
    "def": "yes",
    "fakes": [
     "no",
     "only for isotopes",
     "only for metals",
     "only sometimes",
     "no, always exact",
     "only for heavy elements",
     "no, use decimals",
     "only in organic chemistry"
    ]
   },
   {
    "id": "seed-full-012",
    "term": "Electrons in a neutral atom equal the number of",
    "def": "protons",
    "fakes": [
     "neutrons",
     "protons plus neutrons",
     "mass number",
     "valence shells",
     "isotopes",
     "nucleons",
     "protons minus neutrons",
     "atomic mass"
    ]
   },
   {
    "id": "seed-full-013",
    "term": "Element with 17 protons",
    "def": "chlorine",
    "fakes": [
     "fluorine",
     "sulfur",
     "phosphorus",
     "argon",
     "bromine",
     "silicon",
     "potassium",
     "sodium"
    ]
   },
   {
    "id": "seed-full-014",
    "term": "Neutrons in chlorine (mass 35)",
    "def": "18",
    "fakes": [
     "17",
     "19",
     "16",
     "35",
     "20",
     "15",
     "34",
     "36"
    ]
   },
   {
    "id": "seed-full-015",
    "term": "Neutrons in aluminum (Z 13, mass 26.98)",
    "def": "14",
    "fakes": [
     "13",
     "15",
     "27",
     "12",
     "26",
     "16",
     "11",
     "17"
    ]
   },
   {
    "id": "seed-full-016",
    "term": "Neutrons in iron (Z 26, mass 55.85)",
    "def": "30",
    "fakes": [
     "26",
     "29",
     "56",
     "31",
     "28",
     "25",
     "55",
     "32"
    ]
   },
   {
    "id": "seed-full-017",
    "term": "2 or more atoms bonded together",
    "def": "molecule",
    "fakes": [
     "element",
     "ion",
     "isotope",
     "mixture",
     "alloy",
     "atom",
     "solution",
     "catalyst"
    ]
   },
   {
    "id": "seed-full-018",
    "term": "Atoms of 2 or more different elements bonded",
    "def": "compound",
    "fakes": [
     "molecule",
     "element",
     "mixture",
     "isotope",
     "alloy",
     "ion",
     "solvent",
     "catalyst"
    ]
   },
   {
    "id": "seed-full-019",
    "term": "NaCl: molecule, compound, or both?",
    "def": "compound",
    "fakes": [
     "molecule",
     "both",
     "element",
     "ion",
     "mixture",
     "neither",
     "alloy",
     "polymer"
    ]
   },
   {
    "id": "seed-full-020",
    "term": "O2: molecule, compound, or both?",
    "def": "molecule",
    "fakes": [
     "compound",
     "both",
     "salt",
     "ion",
     "mixture",
     "neither",
     "alloy",
     "isotope"
    ]
   },
   {
    "id": "seed-full-021",
    "term": "A dye: molecule, compound, or both?",
    "def": "both",
    "fakes": [
     "neither",
     "element",
     "mixture",
     "ion",
     "alloy",
     "isotope",
     "salt",
     "solution"
    ]
   },
   {
    "id": "seed-full-022",
    "term": "CO2: best single term",
    "def": "compound",
    "fakes": [
     "molecule",
     "both",
     "element",
     "mixture",
     "ion",
     "alloy",
     "isotope",
     "polymer"
    ]
   },
   {
    "id": "seed-full-023",
    "term": "Why is NaCl not a molecule?",
    "def": "ionic lattice",
    "fakes": [
     "covalent network",
     "metallic bonding",
     "hydrogen bonding",
     "van der Waals forces",
     "crystalline polymer",
     "molecular lattice",
     "covalent lattice",
     "amorphous solid"
    ]
   },
   {
    "id": "seed-full-024",
    "term": "Shell capacities in this class",
    "def": "2, 8, 8",
    "fakes": [
     "2, 8, 18",
     "2, 6, 8",
     "2, 8, 8, 18",
     "2, 4, 8",
     "8, 8, 8",
     "2, 8, 10",
     "2, 10, 8",
     "2, 8, 6"
    ]
   },
   {
    "id": "seed-full-025",
    "term": "Valence electrons for groups 13 to 18",
    "def": "group minus 10",
    "fakes": [
     "group minus 8",
     "group plus 10",
     "group minus 12",
     "group divided by 2",
     "group minus 2",
     "group plus 8",
     "group minus 18",
     "group times 2"
    ]
   },
   {
    "id": "seed-full-026",
    "term": "Valence electrons: carbon",
    "def": "4",
    "fakes": [
     "2",
     "3",
     "5",
     "6",
     "8",
     "1",
     "12",
     "14"
    ]
   },
   {
    "id": "seed-full-027",
    "term": "Valence electrons: nitrogen",
    "def": "5",
    "fakes": [
     "3",
     "4",
     "6",
     "7",
     "2",
     "8",
     "15",
     "1"
    ]
   },
   {
    "id": "seed-full-028",
    "term": "Valence electrons: oxygen",
    "def": "6",
    "fakes": [
     "4",
     "5",
     "7",
     "8",
     "2",
     "16",
     "3",
     "1"
    ]
   },
   {
    "id": "seed-full-029",
    "term": "Valence electrons: chlorine",
    "def": "7",
    "fakes": [
     "5",
     "6",
     "8",
     "17",
     "1",
     "3",
     "4",
     "2"
    ]
   },
   {
    "id": "seed-full-030",
    "term": "Valence electrons: hydrogen",
    "def": "1",
    "fakes": [
     "2",
     "3",
     "4",
     "7",
     "8",
     "0",
     "6",
     "5"
    ]
   },
   {
    "id": "seed-full-031",
    "term": "Unreactive elements with full shells",
    "def": "noble gases",
    "fakes": [
     "alkali metals",
     "halogens",
     "transition metals",
     "alkaline earth metals",
     "metalloids",
     "lanthanides",
     "actinides",
     "rare earths"
    ]
   },
   {
    "id": "seed-full-032",
    "term": "Most likely to bond: He, Ne, Na, or Ar",
    "def": "Na",
    "fakes": [
     "He",
     "Ne",
     "Ar",
     "all equally",
     "none of them",
     "He and Ne",
     "Ar and Ne",
     "none, all stable"
    ]
   },
   {
    "id": "seed-full-033",
    "term": "Why sodium bonds easily",
    "def": "1 valence electron",
    "fakes": [
     "8 valence electrons",
     "full outer shell",
     "7 valence electrons",
     "high electronegativity",
     "2 valence electrons",
     "large atomic radius only",
     "noble gas structure",
     "negative charge"
    ]
   },
   {
    "id": "seed-full-034",
    "term": "Atoms bond to reach how many valence electrons?",
    "def": "8",
    "fakes": [
     "2",
     "6",
     "10",
     "4",
     "18",
     "16",
     "1",
     "12"
    ]
   },
   {
    "id": "seed-full-035",
    "term": "Name of the rule for 8 valence electrons",
    "def": "octet rule",
    "fakes": [
     "duet rule",
     "valence rule",
     "shell rule",
     "quartet rule",
     "bonding rule",
     "electron rule",
     "decet rule",
     "stability rule"
    ]
   },
   {
    "id": "seed-full-036",
    "term": "Strong bonds: primary or secondary?",
    "def": "primary",
    "fakes": [
     "secondary",
     "both equally",
     "neither",
     "tertiary",
     "ionic only",
     "covalent only",
     "hydrogen bonds",
     "van der Waals"
    ]
   },
   {
    "id": "seed-full-037",
    "term": "Hydrogen bonds: primary or secondary?",
    "def": "secondary",
    "fakes": [
     "primary",
     "both equally",
     "neither",
     "tertiary",
     "ionic",
     "covalent",
     "metallic",
     "van der Waals only"
    ]
   },
   {
    "id": "seed-full-038",
    "term": "Two kinds of primary bonds",
    "def": "ionic and covalent",
    "fakes": [
     "ionic and metallic",
     "covalent and hydrogen",
     "metallic and covalent",
     "ionic and van der Waals",
     "hydrogen and van der Waals",
     "covalent and dipole",
     "metallic and hydrogen",
     "ionic and dipole"
    ]
   },
   {
    "id": "seed-full-039",
    "term": "Electrons transferred",
    "def": "ionic",
    "fakes": [
     "covalent",
     "metallic",
     "hydrogen",
     "van der Waals",
     "dipole",
     "coordinate",
     "nonpolar covalent",
     "polar covalent"
    ]
   },
   {
    "id": "seed-full-040",
    "term": "Electrons shared",
    "def": "covalent",
    "fakes": [
     "ionic",
     "metallic",
     "hydrogen",
     "van der Waals",
     "dipole",
     "electrostatic",
     "coordinate ionic",
     "ionic-covalent"
    ]
   },
   {
    "id": "seed-full-041",
    "term": "Ionic bonds form between a metal and a",
    "def": "nonmetal",
    "fakes": [
     "metal",
     "metalloid",
     "noble gas",
     "transition metal",
     "actinide",
     "another metal",
     "polymer",
     "semiconductor"
    ]
   },
   {
    "id": "seed-full-042",
    "term": "Bonds in a polymer backbone",
    "def": "covalent",
    "fakes": [
     "ionic",
     "metallic",
     "hydrogen",
     "van der Waals",
     "dipole",
     "electrostatic",
     "coordinate",
     "ionic-covalent"
    ]
   },
   {
    "id": "seed-full-043",
    "term": "Acid dye bonds to nylon's amine end by what bond?",
    "def": "ionic",
    "fakes": [
     "covalent",
     "hydrogen",
     "van der Waals",
     "metallic",
     "dipole",
     "coordinate covalent",
     "amide",
     "ester"
    ]
   },
   {
    "id": "seed-full-044",
    "term": "Electronegativity increases toward which element?",
    "def": "fluorine",
    "fakes": [
     "chlorine",
     "nitrogen",
     "carbon",
     "francium",
     "hydrogen",
     "sodium",
     "neon",
     "argon"
    ]
   },
   {
    "id": "seed-full-045",
    "term": "Electronegativity direction on the table",
    "def": "up and right",
    "fakes": [
     "down and left",
     "up and left",
     "down and right",
     "left to right only",
     "top to bottom only",
     "diagonal down-right",
     "center outward",
     "right to left"
    ]
   },
   {
    "id": "seed-full-046",
    "term": "Highest electronegativity",
    "def": "fluorine",
    "fakes": [
     "oxygen",
     "chlorine",
     "nitrogen",
     "francium",
     "cesium",
     "carbon",
     "hydrogen",
     "neon"
    ]
   },
   {
    "id": "seed-full-047",
    "term": "Rank F, O, C, Na by electronegativity",
    "def": "F O C Na",
    "fakes": [
     "Na O C F",
     "F O Na C",
     "Na C O F",
     "O C F Na",
     "Na F O C"
    ]
   },
   {
    "id": "seed-full-048",
    "term": "Bonds carbon always forms",
    "def": "4",
    "fakes": [
     "2",
     "3",
     "5",
     "6",
     "8",
     "1",
     "7",
     "0"
    ]
   },
   {
    "id": "seed-full-049",
    "term": "Lone pairs on carbon",
    "def": "0",
    "fakes": [
     "1",
     "2",
     "3",
     "4",
     "6",
     "8",
     "5",
     "7"
    ]
   },
   {
    "id": "seed-full-050",
    "term": "Lone pairs on oxygen",
    "def": "2",
    "fakes": [
     "1",
     "3",
     "0",
     "4",
     "6",
     "5",
     "8",
     "7"
    ]
   },
   {
    "id": "seed-full-051",
    "term": "Lone pairs on nitrogen",
    "def": "1",
    "fakes": [
     "2",
     "0",
     "3",
     "4",
     "6",
     "5",
     "8",
     "7"
    ]
   },
   {
    "id": "seed-full-052",
    "term": "Lone pairs on water's O",
    "def": "2",
    "fakes": [
     "1",
     "3",
     "0",
     "4",
     "6",
     "5",
     "8",
     "7"
    ]
   },
   {
    "id": "seed-full-053",
    "term": "Lone pairs on ammonia's N",
    "def": "1",
    "fakes": [
     "2",
     "0",
     "3",
     "4",
     "6",
     "5",
     "8",
     "7"
    ]
   },
   {
    "id": "seed-full-054",
    "term": "Total lone pairs in O2",
    "def": "4",
    "fakes": [
     "2",
     "6",
     "8",
     "3",
     "5",
     "0",
     "1",
     "7"
    ]
   },
   {
    "id": "seed-full-055",
    "term": "Bond between the two O's in O2",
    "def": "double",
    "fakes": [
     "single",
     "triple",
     "ionic",
     "hydrogen",
     "coordinate",
     "aromatic",
     "van der Waals",
     "metallic"
    ]
   },
   {
    "id": "seed-full-056",
    "term": "Skeletal structure: a carbon sits at every",
    "def": "corner and end",
    "fakes": [
     "corner only",
     "end only",
     "intersection only",
     "vertex and center",
     "bend only",
     "line midpoint",
     "every atom shown",
     "double bond only"
    ]
   },
   {
    "id": "seed-full-057",
    "term": "Skeletal structure: which atoms are hidden?",
    "def": "hydrogens",
    "fakes": [
     "carbons",
     "oxygens",
     "nitrogens",
     "all heteroatoms",
     "halogens",
     "lone pairs",
     "double bonds",
     "all atoms"
    ]
   },
   {
    "id": "seed-full-058",
    "term": "Carbons in a zigzag of 4 lines",
    "def": "5",
    "fakes": [
     "4",
     "3",
     "6",
     "7",
     "8",
     "2",
     "9",
     "10"
    ]
   },
   {
    "id": "seed-full-059",
    "term": "Carbons in a zigzag of n lines",
    "def": "n + 1",
    "fakes": [
     "n",
     "n + 2",
     "2n",
     "n + 3",
     "2n + 1"
    ]
   },
   {
    "id": "seed-full-060",
    "term": "Hidden H on each bare benzene carbon",
    "def": "1",
    "fakes": [
     "2",
     "3",
     "4",
     "0",
     "6",
     "5",
     "8",
     "7"
    ]
   },
   {
    "id": "seed-full-061",
    "term": "Benzene formula",
    "def": "C6H6",
    "fakes": [
     "C6H12",
     "C6H14",
     "C5H6",
     "C7H8",
     "C6H5",
     "C6H10",
     "C4H6",
     "C8H6"
    ]
   },
   {
    "id": "seed-full-062",
    "term": "Phenol (benzene + OH) formula",
    "def": "C6H6O",
    "fakes": [
     "C6H4O2",
     "C6H7O",
     "C7H6O",
     "C6H6O2",
     "C5H4O",
     "C6H8O2",
     "C6H5O",
     "C7H8O"
    ]
   },
   {
    "id": "seed-full-063",
    "term": "Toluene (benzene + CH3) formula",
    "def": "C7H8",
    "fakes": [
     "C6H8",
     "C7H6",
     "C8H10",
     "C7H10",
     "C6H6",
     "C8H8",
     "C7H14",
     "C6H10"
    ]
   },
   {
    "id": "seed-full-064",
    "term": "Pentane formula",
    "def": "C5H12",
    "fakes": [
     "C5H10",
     "C4H10",
     "C6H12",
     "C5H14",
     "C6H14",
     "C5H8",
     "C4H12",
     "C5H16"
    ]
   },
   {
    "id": "seed-full-065",
    "term": "Hexane formula",
    "def": "C6H14",
    "fakes": [
     "C6H12",
     "C5H12",
     "C7H16",
     "C6H16",
     "C6H10",
     "C7H14",
     "C5H14",
     "C6H18"
    ]
   },
   {
    "id": "seed-full-066",
    "term": "All single C-C bonds",
    "def": "alkane",
    "fakes": [
     "aromatic",
     "polymer",
     "monomer",
     "diene",
     "unsaturated hydrocarbon",
     "aromatic ring"
    ]
   },
   {
    "id": "seed-full-067",
    "term": "Has a C=C double bond",
    "def": "alkene",
    "fakes": [
     "aromatic",
     "polymer",
     "monomer",
     "diene only",
     "saturated hydrocarbon",
     "cycloalkane"
    ]
   },
   {
    "id": "seed-full-068",
    "term": "Has a C≡C triple bond",
    "def": "alkyne",
    "fakes": [
     "aromatic",
     "polymer",
     "monomer",
     "diene",
     "saturated hydrocarbon",
     "cycloalkane"
    ]
   },
   {
    "id": "seed-full-069",
    "term": "Ethane: alkane, alkene, or alkyne?",
    "def": "alkane",
    "fakes": [
     "aromatic",
     "none of these",
     "alkane and alkene",
     "cycloalkane",
     "diene",
     "saturated alkene"
    ]
   },
   {
    "id": "seed-full-070",
    "term": "Ethylene: alkane, alkene, or alkyne?",
    "def": "alkene",
    "fakes": [
     "aromatic",
     "none of these",
     "alkene and alkyne",
     "cycloalkane",
     "diene",
     "saturated alkane"
    ]
   },
   {
    "id": "seed-full-071",
    "term": "Acetylene: alkane, alkene, or alkyne?",
    "def": "alkyne",
    "fakes": [
     "aromatic",
     "alcohol",
     "cycloalkane",
     "diene",
     "saturated hydrocarbon",
     "alkyl halide"
    ]
   },
   {
    "id": "seed-full-072",
    "term": "Ethane formula",
    "def": "C2H6",
    "fakes": [
     "C2H4",
     "C2H2",
     "CH4",
     "C3H8",
     "C2H5",
     "C3H6",
     "C4H10",
     "CH2"
    ]
   },
   {
    "id": "seed-full-073",
    "term": "Ethylene formula",
    "def": "C2H4",
    "fakes": [
     "C2H6",
     "C2H2",
     "C3H6",
     "CH4",
     "C2H5",
     "C4H8",
     "C3H4",
     "C2H3"
    ]
   },
   {
    "id": "seed-full-074",
    "term": "Acetylene formula",
    "def": "C2H2",
    "fakes": [
     "C2H4",
     "C2H6",
     "C3H4",
     "CH2",
     "C2H3",
     "C4H2",
     "C3H6",
     "CH4"
    ]
   },
   {
    "id": "seed-full-075",
    "term": "All single bonds: saturated or unsaturated?",
    "def": "saturated",
    "fakes": [
     "aromatic",
     "crystalline",
     "amorphous",
     "conjugated",
     "cross-linked",
     "polar",
     "ionic"
    ]
   },
   {
    "id": "seed-full-076",
    "term": "Has a double bond: saturated or unsaturated?",
    "def": "unsaturated",
    "fakes": [
     "aromatic",
     "partially saturated",
     "crystalline",
     "amorphous",
     "conjugated",
     "cross-linked",
     "branched"
    ]
   },
   {
    "id": "seed-full-077",
    "term": "Who proposed the Macromolecular Hypothesis?",
    "def": "Staudinger",
    "fakes": [
     "Carothers",
     "Ziegler",
     "Natta",
     "Flory",
     "Avogadro",
     "Dalton",
     "Mendeleev",
     "Pauling"
    ]
   },
   {
    "id": "seed-full-078",
    "term": "Macromolecular Hypothesis: repeat units joined by what bonds?",
    "def": "covalent",
    "fakes": [
     "ionic",
     "hydrogen",
     "metallic",
     "van der Waals",
     "dipole-dipole",
     "weak forces",
     "coordinate",
     "London dispersion"
    ]
   },
   {
    "id": "seed-full-079",
    "term": "Before Staudinger: polymers were clumps held by what forces?",
    "def": "weak forces",
    "fakes": [
     "covalent bonds",
     "ionic bonds",
     "strong forces",
     "metallic bonds",
     "coordinate bonds",
     "amide bonds",
     "ester bonds",
     "peptide bonds"
    ]
   },
   {
    "id": "seed-full-080",
    "term": "Staudinger equation: memorize it?",
    "def": "no",
    "fakes": [
     "yes",
     "only sometimes",
     "only partly",
     "only the variables",
     "only for nylon",
     "only qualitatively",
     "only approximately",
     "only the units"
    ]
   },
   {
    "id": "seed-full-081",
    "term": "Units in a monomer",
    "def": "1",
    "fakes": [
     "2",
     "10",
     "100",
     "thousands",
     "0",
     "3",
     "2 to 10",
     "50"
    ]
   },
   {
    "id": "seed-full-082",
    "term": "Units in an oligomer",
    "def": "2 to 10",
    "fakes": [
     "1",
     "10 to 100",
     "thousands",
     "100 to 1000",
     "1 to 2",
     "20 to 50",
     "50 to 100",
     "12 to 20"
    ]
   },
   {
    "id": "seed-full-083",
    "term": "Units in a polymer",
    "def": "thousands",
    "fakes": [
     "hundreds",
     "2 to 10",
     "1",
     "tens",
     "millions",
     "10 to 100",
     "dozens",
     "100"
    ]
   },
   {
    "id": "seed-full-084",
    "term": "The piece in brackets that repeats n times",
    "def": "repeat unit",
    "fakes": [
     "monomer",
     "oligomer",
     "end group",
     "side chain",
     "backbone",
     "functional group",
     "degree of polymerization",
     "copolymer"
    ]
   },
   {
    "id": "seed-full-085",
    "term": "Addition monomer template",
    "def": "H2C=CHR",
    "fakes": [
     "HC≡CR",
     "H2C-CH2R",
     "RHC=CHR",
     "H2N-R-COOH",
     "HOOC-R-COOH",
     "H2C=CR2",
     "RCH2-CH2R",
     "HO-R-OH"
    ]
   },
   {
    "id": "seed-full-086",
    "term": "Monomer of polyethylene",
    "def": "ethylene",
    "fakes": [
     "propylene",
     "styrene",
     "vinyl chloride",
     "acetylene",
     "ethane",
     "butylene",
     "ethylene glycol",
     "ethanol"
    ]
   },
   {
    "id": "seed-full-087",
    "term": "Monomer of polypropylene",
    "def": "propylene",
    "fakes": [
     "ethylene",
     "styrene",
     "vinyl chloride",
     "propane",
     "butylene",
     "propylene glycol",
     "isobutylene"
    ]
   },
   {
    "id": "seed-full-088",
    "term": "Monomer of polystyrene",
    "def": "styrene",
    "fakes": [
     "ethylene",
     "propylene",
     "vinyl chloride",
     "benzene",
     "toluene",
     "phenol",
     "butadiene",
     "vinyl acetate"
    ]
   },
   {
    "id": "seed-full-089",
    "term": "Monomer of PVC",
    "def": "vinyl chloride",
    "fakes": [
     "ethylene",
     "propylene",
     "styrene",
     "vinyl acetate",
     "vinylidene chloride",
     "chloroethane",
     "ethylene dichloride",
     "vinyl fluoride"
    ]
   },
   {
    "id": "seed-full-090",
    "term": "R group of ethylene",
    "def": "H",
    "fakes": [
     "CH3",
     "Cl",
     "benzene ring",
     "OH",
     "C2H5",
     "CH2",
     "F",
     "NH2"
    ]
   },
   {
    "id": "seed-full-091",
    "term": "R group of propylene",
    "def": "CH3",
    "fakes": [
     "H",
     "Cl",
     "benzene ring",
     "C2H5",
     "OH",
     "CH2",
     "C3H7",
     "F"
    ]
   },
   {
    "id": "seed-full-092",
    "term": "R group of styrene",
    "def": "benzene ring",
    "fakes": [
     "CH3",
     "Cl",
     "H",
     "phenol group",
     "naphthalene ring",
     "OH",
     "C2H5",
     "cyclohexane ring"
    ]
   },
   {
    "id": "seed-full-093",
    "term": "R group of vinyl chloride",
    "def": "Cl",
    "fakes": [
     "H",
     "CH3",
     "benzene ring",
     "F",
     "Br",
     "OH",
     "NH2",
     "C2H5"
    ]
   },
   {
    "id": "seed-full-094",
    "term": "Polymer made from H2C=CHCl",
    "def": "PVC",
    "fakes": [
     "PE",
     "PP",
     "PS",
     "PET",
     "nylon-6,6",
     "PVA",
     "PTFE",
     "PVDC"
    ]
   },
   {
    "id": "seed-full-095",
    "term": "PE repeat unit formula",
    "def": "C2H4",
    "fakes": [
     "C3H6",
     "C2H6",
     "C8H8",
     "C2H2",
     "C4H8",
     "C2H5",
     "C3H4",
     "C5H10"
    ]
   },
   {
    "id": "seed-full-096",
    "term": "PP repeat unit formula",
    "def": "C3H6",
    "fakes": [
     "C2H4",
     "C3H8",
     "C8H8",
     "C3H4",
     "C2H6",
     "C4H8",
     "C3H7",
     "C4H6"
    ]
   },
   {
    "id": "seed-full-097",
    "term": "PS repeat unit formula",
    "def": "C8H8",
    "fakes": [
     "C2H4",
     "C3H6",
     "C6H6",
     "C8H10",
     "C7H8",
     "C6H5",
     "C9H10",
     "C8H6"
    ]
   },
   {
    "id": "seed-full-098",
    "term": "In addition polymerization, what opens up?",
    "def": "the double bond",
    "fakes": [
     "the triple bond",
     "the ring",
     "the ester bond",
     "the amide bond",
     "a single bond",
     "the benzene ring",
     "the hydroxyl group",
     "the carbonyl group"
    ]
   },
   {
    "id": "seed-full-099",
    "term": "Addition polymerization: anything lost?",
    "def": "no",
    "fakes": [
     "yes",
     "water",
     "HCl",
     "byproduct",
     "only sometimes",
     "yes, a small molecule",
     "alcohol",
     "ammonia"
    ]
   },
   {
    "id": "seed-full-100",
    "term": "Condensation polymerization loses what?",
    "def": "water",
    "fakes": [
     "HCl",
     "ammonia",
     "nothing",
     "oxygen",
     "ethylene glycol",
     "methanol",
     "carbon dioxide",
     "hydrogen"
    ]
   },
   {
    "id": "seed-full-101",
    "term": "Nylon-6,6: addition or condensation?",
    "def": "condensation",
    "fakes": [
     "addition",
     "chain-growth",
     "free-radical",
     "ring-opening",
     "neither",
     "both",
     "thermoset",
     "anionic polymerization"
    ]
   },
   {
    "id": "seed-full-102",
    "term": "PET: addition or condensation?",
    "def": "condensation",
    "fakes": [
     "addition",
     "chain-growth",
     "free-radical",
     "ring-opening",
     "neither",
     "both",
     "thermoset",
     "anionic polymerization"
    ]
   },
   {
    "id": "seed-full-103",
    "term": "Nylon-6,6 amine monomer",
    "def": "1,6-diaminohexane",
    "fakes": [
     "1,4-diaminobutane",
     "1,8-diaminooctane",
     "ethylenediamine",
     "adipic acid",
     "terephthalic acid",
     "1,6-hexanediol",
     "1,5-diaminopentane",
     "ethylene glycol"
    ]
   },
   {
    "id": "seed-full-104",
    "term": "Nylon-6,6 acid monomer",
    "def": "adipic acid",
    "fakes": [
     "terephthalic acid",
     "sebacic acid",
     "succinic acid",
     "1,6-diaminohexane",
     "ethylene glycol",
     "oxalic acid",
     "glutaric acid",
     "phthalic acid"
    ]
   },
   {
    "id": "seed-full-105",
    "term": "Carbons in each nylon-6,6 monomer",
    "def": "6",
    "fakes": [
     "4",
     "5",
     "7",
     "8",
     "10",
     "2",
     "12",
     "3"
    ]
   },
   {
    "id": "seed-full-106",
    "term": "Nylon-6,6 link type",
    "def": "amide",
    "fakes": [
     "ester",
     "ether",
     "urethane",
     "carbonate",
     "anhydride",
     "hydrogen bond"
    ]
   },
   {
    "id": "seed-full-107",
    "term": "Amide link atoms",
    "def": "C(=O)-NH",
    "fakes": [
     "C(=O)-O",
     "C(=O)-O-C",
     "O-C-O",
     "C(=O)-NH2",
     "N-H",
     "C(=O)-Cl",
     "C-O-C"
    ]
   },
   {
    "id": "seed-full-108",
    "term": "Nylon-6,6 repeat unit formula",
    "def": "C12H22N2O2",
    "fakes": [
     "C12H24N2O2",
     "C10H18N2O2",
     "C12H22N2O3",
     "C14H26N2O2",
     "C12H20N2O2",
     "C10H20N2O2",
     "C12H22N2O",
     "C12H22NO2"
    ]
   },
   {
    "id": "seed-full-109",
    "term": "Nylon-6,6 repeat unit molar mass",
    "def": "226.32",
    "fakes": [
     "212.16",
     "192.16",
     "254.37",
     "216.32",
     "236.32",
     "200.32",
     "246.32",
     "208.32"
    ]
   },
   {
    "id": "seed-full-110",
    "term": "PET acid monomer",
    "def": "terephthalic acid",
    "fakes": [
     "adipic acid",
     "phthalic acid",
     "isophthalic acid",
     "benzoic acid",
     "oxalic acid",
     "succinic acid",
     "sebacic acid",
     "ethylene glycol"
    ]
   },
   {
    "id": "seed-full-111",
    "term": "PET alcohol monomer",
    "def": "ethylene glycol",
    "fakes": [
     "propylene glycol",
     "methanol",
     "ethanol",
     "1,6-hexanediol",
     "glycerol",
     "ethylene oxide",
     "terephthalic acid"
    ]
   },
   {
    "id": "seed-full-112",
    "term": "PET link type",
    "def": "ester",
    "fakes": [
     "amide",
     "ether",
     "urethane",
     "imide",
     "carbonate",
     "anhydride",
     "hydrogen bond",
     "amine"
    ]
   },
   {
    "id": "seed-full-113",
    "term": "Ester link atoms",
    "def": "C(=O)-O",
    "fakes": [
     "C(=O)-NH",
     "O-C-O",
     "C(=O)-Cl",
     "N-H",
     "C(=O)-NH2",
     "C-N-C"
    ]
   },
   {
    "id": "seed-full-114",
    "term": "PET repeat unit formula",
    "def": "C10H8O4",
    "fakes": [
     "C10H10O4",
     "C8H6O4",
     "C10H8O3",
     "C12H10O4",
     "C10H8O5",
     "C9H8O4",
     "C10H6O4",
     "C10H8O2"
    ]
   },
   {
    "id": "seed-full-115",
    "term": "PET repeat unit molar mass",
    "def": "192.16",
    "fakes": [
     "194.16",
     "176.16",
     "226.32",
     "180.16",
     "206.16",
     "164.16",
     "212.16",
     "198.16"
    ]
   },
   {
    "id": "seed-full-116",
    "term": "Nylon-6,6: homopolymer or heteropolymer?",
    "def": "homopolymer",
    "fakes": [
     "heteropolymer",
     "copolymer",
     "block copolymer",
     "random copolymer",
     "alternating copolymer",
     "biopolymer",
     "graft copolymer",
     "cross-linked polymer"
    ]
   },
   {
    "id": "seed-full-117",
    "term": "Number of classification categories",
    "def": "6",
    "fakes": [
     "4",
     "5",
     "7",
     "8",
     "3",
     "10",
     "2",
     "9"
    ]
   },
   {
    "id": "seed-full-118",
    "term": "Classification category: natural vs synthetic",
    "def": "origin",
    "fakes": [
     "chain architecture",
     "monomer composition",
     "monomer arrangement",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-full-119",
    "term": "Classification category: homo vs hetero",
    "def": "monomer composition",
    "fakes": [
     "origin",
     "chain architecture",
     "monomer arrangement",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-full-120",
    "term": "Classification category: linear vs branched",
    "def": "chain architecture",
    "fakes": [
     "origin",
     "monomer composition",
     "monomer arrangement",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-full-121",
    "term": "Classification category: random vs block",
    "def": "monomer arrangement",
    "fakes": [
     "origin",
     "monomer composition",
     "chain architecture",
     "material behavior",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-full-122",
    "term": "Classification category: thermoplastic vs thermoset",
    "def": "material behavior",
    "fakes": [
     "origin",
     "monomer composition",
     "chain architecture",
     "monomer arrangement",
     "crystallinity",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-full-123",
    "term": "Classification category: crystalline vs amorphous",
    "def": "crystallinity",
    "fakes": [
     "origin",
     "monomer composition",
     "chain architecture",
     "monomer arrangement",
     "material behavior",
     "molecular weight",
     "tacticity",
     "morphology"
    ]
   },
   {
    "id": "seed-full-124",
    "term": "Cellulose origin",
    "def": "natural",
    "fakes": [
     "synthetic",
     "semi-synthetic",
     "man-made",
     "petroleum-based",
     "artificial",
     "lab-synthesized",
     "engineered",
     "industrial"
    ]
   },
   {
    "id": "seed-full-125",
    "term": "Protein origin",
    "def": "natural",
    "fakes": [
     "synthetic",
     "semi-synthetic",
     "man-made",
     "petroleum-based",
     "artificial",
     "lab-synthesized",
     "engineered",
     "industrial"
    ]
   },
   {
    "id": "seed-full-126",
    "term": "Polyethylene origin",
    "def": "synthetic",
    "fakes": [
     "natural",
     "semi-synthetic",
     "biological",
     "plant-derived",
     "animal-derived",
     "fermented",
     "naturally occurring",
     "bio-based"
    ]
   },
   {
    "id": "seed-full-127",
    "term": "Nylon origin",
    "def": "synthetic",
    "fakes": [
     "natural",
     "semi-synthetic",
     "biological",
     "plant-derived",
     "animal-derived",
     "fermented",
     "naturally occurring",
     "bio-based"
    ]
   },
   {
    "id": "seed-full-128",
    "term": "Rayon origin",
    "def": "semi-synthetic",
    "fakes": [
     "natural",
     "synthetic",
     "biopolymer",
     "fully synthetic",
     "man-made",
     "petroleum-based",
     "naturally occurring",
     "animal-derived"
    ]
   },
   {
    "id": "seed-full-129",
    "term": "Cellulose acetate origin",
    "def": "semi-synthetic",
    "fakes": [
     "natural",
     "synthetic",
     "biopolymer",
     "fully synthetic",
     "man-made",
     "petroleum-based",
     "naturally occurring",
     "animal-derived"
    ]
   },
   {
    "id": "seed-full-130",
    "term": "Rayon is made by modifying what?",
    "def": "cellulose",
    "fakes": [
     "starch",
     "protein",
     "petroleum",
     "ethylene",
     "collagen",
     "chitin",
     "lignin",
     "keratin"
    ]
   },
   {
    "id": "seed-full-131",
    "term": "One type of repeat unit",
    "def": "homopolymer",
    "fakes": [
     "heteropolymer",
     "copolymer",
     "block copolymer",
     "random copolymer",
     "alternating copolymer",
     "graft copolymer",
     "biopolymer",
     "oligomer"
    ]
   },
   {
    "id": "seed-full-132",
    "term": "Two or more types of repeat unit",
    "def": "heteropolymer",
    "fakes": [
     "homopolymer",
     "monomer",
     "oligomer",
     "biopolymer",
     "cross-linked polymer",
     "thermoplastic",
     "thermoset",
     "branched polymer"
    ]
   },
   {
    "id": "seed-full-133",
    "term": "A protein is a heteropolymer and a",
    "def": "biopolymer",
    "fakes": [
     "homopolymer",
     "thermoplastic",
     "thermoset",
     "monomer",
     "oligomer",
     "synthetic polymer",
     "cross-linked polymer",
     "elastomer"
    ]
   },
   {
    "id": "seed-full-134",
    "term": "Copolymer: ABABAB",
    "def": "alternating",
    "fakes": [
     "block",
     "random",
     "graft",
     "homopolymer",
     "branched",
     "cross-linked",
     "star",
     "comb"
    ]
   },
   {
    "id": "seed-full-135",
    "term": "Copolymer: AAABBB",
    "def": "block",
    "fakes": [
     "alternating",
     "random",
     "graft",
     "homopolymer",
     "branched",
     "cross-linked",
     "star",
     "linear"
    ]
   },
   {
    "id": "seed-full-136",
    "term": "Copolymer: ABBAAB",
    "def": "random",
    "fakes": [
     "alternating",
     "block",
     "graft",
     "homopolymer",
     "branched",
     "cross-linked",
     "star",
     "linear"
    ]
   },
   {
    "id": "seed-full-137",
    "term": "Copolymer: A backbone with B side chains",
    "def": "graft",
    "fakes": [
     "alternating",
     "block",
     "random",
     "cross-linked",
     "star",
     "linear",
     "homopolymer",
     "thermoset"
    ]
   },
   {
    "id": "seed-full-138",
    "term": "Chain architecture: chains tied together",
    "def": "cross-linked",
    "fakes": [
     "branched",
     "linear",
     "graft",
     "star",
     "random",
     "alternating",
     "block",
     "ladder"
    ]
   },
   {
    "id": "seed-full-139",
    "term": "Chain architecture: side branches off the main chain",
    "def": "branched",
    "fakes": [
     "linear",
     "cross-linked",
     "star",
     "random",
     "alternating",
     "block",
     "ladder",
     "network"
    ]
   },
   {
    "id": "seed-full-140",
    "term": "Softens when heated, re-melts",
    "def": "thermoplastic",
    "fakes": [
     "thermoset",
     "crystalline",
     "amorphous",
     "elastomer",
     "cross-linked",
     "biopolymer",
     "copolymer",
     "homopolymer"
    ]
   },
   {
    "id": "seed-full-141",
    "term": "Cross-linked, won't re-melt",
    "def": "thermoset",
    "fakes": [
     "thermoplastic",
     "elastomer",
     "semi-crystalline",
     "amorphous",
     "crystalline",
     "copolymer",
     "homopolymer",
     "monomer"
    ]
   },
   {
    "id": "seed-full-142",
    "term": "Stretches and snaps back",
    "def": "elastomer",
    "fakes": [
     "thermoset",
     "thermoplastic",
     "crystalline",
     "amorphous",
     "semi-crystalline",
     "copolymer",
     "homopolymer",
     "plasticizer"
    ]
   },
   {
    "id": "seed-full-143",
    "term": "Recyclable by melting: thermoplastic or thermoset?",
    "def": "thermoplastic",
    "fakes": [
     "thermoset",
     "elastomer",
     "only thermoset",
     "both types",
     "neither type",
     "only PVC",
     "only polyester",
     "depends on the additive"
    ]
   },
   {
    "id": "seed-full-144",
    "term": "Ordered, tightly packed chains",
    "def": "crystalline",
    "fakes": [
     "amorphous",
     "semi-crystalline",
     "thermoset",
     "elastomer",
     "branched",
     "cross-linked",
     "thermoplastic",
     "glassy"
    ]
   },
   {
    "id": "seed-full-145",
    "term": "Disordered chains",
    "def": "amorphous",
    "fakes": [
     "crystalline",
     "semi-crystalline",
     "cross-linked",
     "thermoset",
     "helical",
     "linear",
     "thermoplastic",
     "elastomeric"
    ]
   },
   {
    "id": "seed-full-146",
    "term": "Has both crystalline and amorphous regions",
    "def": "semi-crystalline",
    "fakes": [
     "crystalline",
     "amorphous",
     "thermoset",
     "elastomer",
     "copolymer",
     "homopolymer",
     "cross-linked",
     "glassy"
    ]
   },
   {
    "id": "seed-full-147",
    "term": "Most polymers are",
    "def": "semi-crystalline",
    "fakes": [
     "fully crystalline",
     "fully amorphous",
     "thermosets",
     "elastomers",
     "cross-linked",
     "homopolymers",
     "copolymers",
     "glassy"
    ]
   },
   {
    "id": "seed-full-148",
    "term": "Milk jug polyethylene",
    "def": "HDPE",
    "fakes": [
     "LLDPE",
     "PP",
     "PET",
     "PVC",
     "PS",
     "nylon-6,6",
     "UHMWPE"
    ]
   },
   {
    "id": "seed-full-149",
    "term": "Plastic bag polyethylene",
    "def": "LDPE",
    "fakes": [
     "polycarbonate",
     "PP",
     "PET",
     "PVC",
     "PS",
     "nylon-6,6",
     "UHMWPE"
    ]
   },
   {
    "id": "seed-full-150",
    "term": "More branched: HDPE or LDPE?",
    "def": "LDPE",
    "fakes": [
     "both equally",
     "neither",
     "PP",
     "PET",
     "PVC",
     "PS"
    ]
   },
   {
    "id": "seed-full-151",
    "term": "More crystalline: HDPE or LDPE?",
    "def": "HDPE",
    "fakes": [
     "both equally",
     "neither",
     "PP",
     "PET",
     "PVC",
     "PS",
     "LLDPE"
    ]
   },
   {
    "id": "seed-full-152",
    "term": "Branching makes crystallinity go",
    "def": "down",
    "fakes": [
     "up",
     "stay the same",
     "up then down",
     "to zero",
     "up sharply",
     "unpredictably",
     "down then up",
     "to 100%"
    ]
   },
   {
    "id": "seed-full-153",
    "term": "Lab 1 cross-linked polymer",
    "def": "poly(acrylic acid)",
    "fakes": [
     "polyethylene",
     "polystyrene",
     "poly(vinyl alcohol)",
     "nylon-6,6",
     "PET",
     "polypropylene",
     "poly(acrylamide)",
     "PVC"
    ]
   },
   {
    "id": "seed-full-154",
    "term": "Cross-linked polymer in solvent or base",
    "def": "swells",
    "fakes": [
     "dissolves",
     "melts",
     "shrinks",
     "crystallizes",
     "evaporates",
     "decomposes",
     "hardens",
     "liquefies"
    ]
   },
   {
    "id": "seed-full-155",
    "term": "Repeat-unit molar mass: count atoms where?",
    "def": "inside the brackets",
    "fakes": [
     "across the whole chain",
     "at the chain ends",
     "in the side groups only",
     "in the backbone only",
     "per monomer pair",
     "outside the parentheses",
     "at the crosslink points"
    ]
   },
   {
    "id": "seed-full-156",
    "term": "Atomic mass of C",
    "def": "12.01",
    "fakes": [
     "14.01",
     "16.00",
     "1.008",
     "12.00",
     "13.01",
     "10.81",
     "11.01",
     "24.02"
    ]
   },
   {
    "id": "seed-full-157",
    "term": "Atomic mass of H",
    "def": "1.008",
    "fakes": [
     "2.016",
     "1.01",
     "4.003",
     "12.01",
     "0.008",
     "1.80",
     "16.00",
     "1.16"
    ]
   },
   {
    "id": "seed-full-158",
    "term": "Atomic mass of N",
    "def": "14.01",
    "fakes": [
     "12.01",
     "16.00",
     "15.01",
     "14.00",
     "28.02",
     "7.01",
     "13.01",
     "10.01"
    ]
   },
   {
    "id": "seed-full-159",
    "term": "Atomic mass of O",
    "def": "16.00",
    "fakes": [
     "14.01",
     "18.00",
     "8.00",
     "20.00",
     "32.00",
     "12.01",
     "17.00",
     "6.00"
    ]
   },
   {
    "id": "seed-full-160",
    "term": "DP stands for",
    "def": "degree of polymerization",
    "fakes": [
     "degree of polydispersity",
     "dispersion percentage",
     "density of polymer",
     "degree of plasticity",
     "dipole potential",
     "polymerization rate",
     "doubling point",
     "depolymerization"
    ]
   },
   {
    "id": "seed-full-161",
    "term": "DP = polymer molar mass divided by the",
    "def": "repeat-unit molar mass",
    "fakes": [
     "monomer count",
     "number of chains",
     "total molar mass",
     "molecular weight of solvent",
     "DP squared",
     "number of repeat units",
     "Avogadro's number",
     "chain length"
    ]
   },
   {
    "id": "seed-full-162",
    "term": "Polymer molar mass = DP times the",
    "def": "repeat-unit molar mass",
    "fakes": [
     "monomer count",
     "number of chains",
     "Avogadro's number",
     "DP squared",
     "degree of crystallinity",
     "molecular weight of solvent",
     "chain length",
     "number of repeat units"
    ]
   },
   {
    "id": "seed-full-163",
    "term": "DP is rounded to a",
    "def": "whole number",
    "fakes": [
     "decimal",
     "percentage",
     "fraction",
     "power of ten",
     "nearest hundred",
     "nearest thousand",
     "negative number",
     "ratio"
    ]
   },
   {
    "id": "seed-full-164",
    "term": "DP of 50,000 g/mol polyethylene",
    "def": "1783",
    "fakes": [
     "1428",
     "1250",
     "892",
     "3571",
     "2000",
     "1000",
     "500",
     "3566"
    ]
   },
   {
    "id": "seed-full-165",
    "term": "DP of 20,000 g/mol PET",
    "def": "104",
    "fakes": [
     "52",
     "208",
     "96",
     "120",
     "200",
     "80",
     "156",
     "41"
    ]
   },
   {
    "id": "seed-full-166",
    "term": "Tg stands for",
    "def": "glass transition temperature",
    "fakes": [
     "melting temperature",
     "gelation temperature",
     "glass transformation time",
     "growth temperature",
     "gel point temperature",
     "glassy tensile strength",
     "global temperature"
    ]
   },
   {
    "id": "seed-full-167",
    "term": "Tm stands for",
    "def": "melting temperature",
    "fakes": [
     "glass transition temperature",
     "molar temperature",
     "maximum temperature",
     "melt time",
     "mechanical toughness",
     "monomer temperature",
     "minimum temperature"
    ]
   },
   {
    "id": "seed-full-168",
    "term": "Glassy to rubbery",
    "def": "Tg",
    "fakes": [
     "Tm",
     "Td",
     "Tc",
     "Tb",
     "Tx",
     "boiling point",
     "melting point",
     "flash point"
    ]
   },
   {
    "id": "seed-full-169",
    "term": "Crystalline regions melt",
    "def": "Tm",
    "fakes": [
     "Tg",
     "Td",
     "Tc",
     "Tb",
     "Tx",
     "boiling point",
     "glass transition",
     "decomposition point"
    ]
   },
   {
    "id": "seed-full-170",
    "term": "Tg governs which regions?",
    "def": "amorphous",
    "fakes": [
     "crystalline",
     "semi-crystalline",
     "cross-linked",
     "both regions",
     "neither region",
     "linear regions",
     "branched regions",
     "elastomeric regions"
    ]
   },
   {
    "id": "seed-full-171",
    "term": "Tm governs which regions?",
    "def": "crystalline",
    "fakes": [
     "amorphous",
     "semi-crystalline",
     "cross-linked",
     "both regions",
     "neither region",
     "glassy regions only",
     "branched regions",
     "elastomeric regions"
    ]
   },
   {
    "id": "seed-full-172",
    "term": "Dry spaghetti: above or below Tg?",
    "def": "below",
    "fakes": [
     "above",
     "at",
     "near",
     "well above",
     "equal to",
     "unrelated to",
     "above Tm",
     "at Tm"
    ]
   },
   {
    "id": "seed-full-173",
    "term": "Cooked spaghetti: above or below Tg?",
    "def": "above",
    "fakes": [
     "below",
     "at",
     "near",
     "well below",
     "equal to",
     "unrelated to",
     "below Tm",
     "at Tm"
    ]
   },
   {
    "id": "seed-full-174",
    "term": "Fully amorphous polymer lacks which transition?",
    "def": "Tm",
    "fakes": [
     "Tg",
     "Td",
     "Tc",
     "Tb",
     "Tx",
     "boiling point",
     "decomposition point",
     "flash point"
    ]
   },
   {
    "id": "seed-full-175",
    "term": "Example polymer with Tg but no Tm",
    "def": "polystyrene",
    "fakes": [
     "polyethylene",
     "polypropylene",
     "PET",
     "nylon-6,6",
     "HDPE",
     "LDPE",
     "UHMWPE",
     "PP"
    ]
   },
   {
    "id": "seed-full-176",
    "term": "Dye polyester above or below Tg?",
    "def": "above",
    "fakes": [
     "below",
     "at",
     "near",
     "well below",
     "equal to",
     "unrelated to",
     "below Tm",
     "at Tm"
    ]
   },
   {
    "id": "seed-full-177",
    "term": "Free-radical mechanism on the exam?",
    "def": "no",
    "fakes": [
     "yes",
     "only for addition polymers",
     "only for PE",
     "sometimes",
     "only on the final",
     "only for condensation",
     "yes but briefly",
     "only in lab"
    ]
   }
  ]
 }
];
window.SEED_RETIRED = ["seed-pcc101-structures"];
