// Regenerates decks/seed.js from decks/src/*.txt. Run: node tools/build-seed.js
// The output is committed, so the app itself needs no build step.
const fs = require('fs');
const path = require('path');
const FL = require('../js/core.js');

const root = path.join(__dirname, '..');
const read = (f) => fs.readFileSync(path.join(root, 'decks/src', f), 'utf8');

const exam = FL.parseImport(read('pcc101-exam1.txt'), '\t').map((c, i) => ({
  id: 'seed-exam1-' + String(i + 1).padStart(3, '0'), term: c.term, def: c.def,
}));

const structures = FL.parseImport(read('pcc101-structures.txt'), '\t').map((c, i) => {
  const s = FL.stripImageNote(c.term);
  const n = String(i + 1).padStart(2, '0');
  return { id: 'seed-struct-' + n, term: s.term, def: c.def, termImg: 'decks/pcc-structures/' + n + '.png' };
});

// Bump a deck's version whenever its cards change, so browsers that already
// have the old copy replace it on next load.
const seed = [
  { id: 'seed-pcc101-exam1', version: 2, name: 'PCC 101 Exam 1', folder: 'PCC 101', cards: exam },
  { id: 'seed-pcc101-structures', version: 2, name: 'PCC 101 Structures', folder: 'PCC 101', cards: structures },
];

const out = '// Generated by tools/build-seed.js from decks/src/*.txt. Do not edit by hand.\n' +
  'window.SEED_DECKS = ' + JSON.stringify(seed, null, 1) + ';\n';
fs.writeFileSync(path.join(root, 'decks/seed.js'), out, 'utf8');
console.log('seed decks:', seed.map((d) => d.name + ' (' + d.cards.length + ')').join(', '));
