// Regenerates decks/seed.js from decks/src/*.txt (and fake answers from
// decks/src/pcc101-fakes.json, if present). Run: node tools/build-seed.js
// The output is committed, so the app itself needs no build step.
const fs = require('fs');
const path = require('path');
const FL = require('../js/core.js');

const root = path.join(__dirname, '..');
const read = (f) => fs.readFileSync(path.join(root, 'decks/src', f), 'utf8');

// Fake answers: exact source term line (structure terms keep their
// "(add image NN.png)" note) -> array of wrong answers.
const fakesFile = path.join(root, 'decks/src/pcc101-fakes.json');
const fakesByTerm = fs.existsSync(fakesFile) ? JSON.parse(fs.readFileSync(fakesFile, 'utf8')) : {};
const usedKeys = new Set();
const stats = { cards: 0, withFakes: 0, fakes: 0, dropped: 0, dupes: 0, droppedList: [] };

// Attach cleaned fakes for the card whose source term line is `srcTerm`.
function withFakes(card, srcTerm) {
  stats.cards++;
  const raw = fakesByTerm[srcTerm];
  if (!raw) return card;
  usedKeys.add(srcTerm);
  const r = FL.cleanFakes(raw, card.def);
  stats.dropped += r.dropped;
  stats.dupes += r.dupes;
  if (r.dropped) {
    const kept = new Set(r.fakes.map(FL.normalize));
    raw.filter((f) => String(f).trim() && !kept.has(FL.normalize(f))).forEach((f) => stats.droppedList.push(card.def + '  <-  ' + f));
  }
  if (r.fakes.length) { stats.withFakes++; stats.fakes += r.fakes.length; card.fakes = r.fakes; }
  return card;
}

const full = FL.parseImport(read('pcc101-exam1.txt'), '	').map((c, i) => withFakes({
  id: 'seed-full-' + String(i + 1).padStart(3, '0'), term: c.term, def: c.def,
}, c.term));

const core = FL.parseImport(read('pcc101-core.txt'), '	').map((c, i) => withFakes({
  id: 'seed-core-' + String(i + 1).padStart(3, '0'), term: c.term, def: c.def,
}, c.term));

const structures = FL.parseImport(read('pcc101-structures.txt'), '	').map((c, i) => {
  const s = FL.stripImageNote(c.term);
  const n = String(i + 1).padStart(2, '0');
  return withFakes({ id: 'seed-struct-' + n, term: s.term, def: c.def, termImg: 'decks/pcc-structures/' + n + '.png' }, c.term);
});

// Bump a deck's version whenever its cards change, so browsers that already
// have the old copy pick up the new cards (progress on unchanged cards is kept).
const seed = [
  { id: 'seed-pcc101-exam1', version: 5, name: 'PCC 101 Exam 1', folder: 'PCC 101', cards: core.concat(structures) },
  { id: 'seed-pcc101-exam1-full', version: 3, name: 'PCC 101 Exam 1 (all 177 text cards)', folder: 'PCC 101', cards: full },
];

// Built-in decks that no longer ship. Removed from storage if still present.
const retired = ['seed-pcc101-structures'];

const out = '// Generated by tools/build-seed.js from decks/src/*.txt. Do not edit by hand.\n' +
  'window.SEED_DECKS = ' + JSON.stringify(seed, null, 1) + ';\n' +
  'window.SEED_RETIRED = ' + JSON.stringify(retired) + ';\n';
fs.writeFileSync(path.join(root, 'decks/seed.js'), out, 'utf8');
console.log('seed decks:', seed.map((d) => d.name + ' (' + d.cards.length + ', ' + d.cards.filter((c) => c.fakes).length + ' with fakes)').join(', '));
const keys = Object.keys(fakesByTerm);
const unmatched = keys.filter((k) => !usedKeys.has(k));
console.log('fakes: ' + keys.length + ' terms in pcc101-fakes.json; ' + stats.withFakes + ' of ' + stats.cards + ' seed cards got fakes (' + stats.fakes + ' fakes)');
console.log('fakes dropped because they match the answer or grade as correct: ' + stats.dropped + (stats.dupes ? '; duplicates removed: ' + stats.dupes : ''));
stats.droppedList.forEach((l) => console.log('  dropped: ' + l));
console.log('unmatched fake keys: ' + unmatched.length);
unmatched.forEach((k) => console.log('  unmatched: ' + k));
